
  const perguntasOLD = {
    'pergunta_1':'Qual a cor do céu?',
    'pergunta_1_alternativa_1':'Vermelho',
    'pergunta_1_alternativa_2':'Verde',
    'pergunta_1_alternativa_3':'Azul',
    'pergunta_1_alternativa_4':'Amarelo',
    'pergunta_1_resposta_correta':'Azul',
    'pergunta_1_justificativa':'O céu é azul por causa da dispersão da luz do sol nas moléculas de ar da atmosfera',
    //----------------------------------
    'pergunta_2':'Quem foi a primeira pessoa a viajar no Espaço?',
    'pergunta_2_alternativa_1':'Yuri Gagarin',
    'pergunta_2_alternativa_2':'A cadela Laika',
    'pergunta_2_alternativa_3':'Neil Armstrong',
    'pergunta_2_alternativa_4':'Buzz Aldrin',
    'pergunta_2_resposta_correta':'Yuri Gagarin',
    'pergunta_2_justificativa':'O russo Yuri Gagarin (1934-1968) foi a primeira pessoa a viajar para o espaço, o que aconteceu em 12 de abril de 1961.',
    //----------------------------------
    
  }

  const perguntas = {
    'pergunta_1':'De acordo com a Resolução Municipal nº 244/14 - Regimento Interno da Câmara Municipal de Caxias do Sul, a Câmara exerce sua função legislativa por meio de:',
    'pergunta_1_alternativa_1':'I - Emendas à Lei Orgânica; II - Leis Complementares; III - Leis Ordinárias',
    'pergunta_1_alternativa_2':'I - Leis Complementares; II - Leis Ordinárias; III - Decretos Legislativos',
    'pergunta_1_alternativa_3':'I - Emendas à Lei Orgânica; II - Leis Complementares; III - Leis Ordinárias; IV - Decretos Legislativos',
    'pergunta_1_alternativa_4':'I - Emendas à Lei Orgânica; II - Leis Complementares; III - Leis Ordinárias; IV - Decretos Legislativos; V - Medidas Provisórias',
    'pergunta_1_resposta_correta':'I - Emendas à Lei Orgânica; II - Leis Complementares; III - Leis Ordinárias; IV - Decretos Legislativos',
    'pergunta_1_justificativa':'Conforme o Regimento Interno, a função legislativa é exercida através de Emendas à Lei Orgânica, Leis Complementares, Leis Ordinárias e Decretos Legislativos. Medidas Provisórias são de competência do Prefeito.',

    'pergunta_2':'Em conformidade com o Regimento Interno da Câmara Municipal de Caxias do Sul, analise as afirmações: I - Uma das funções da Câmara Municipal é julgar o Prefeito, o Vice-Prefeito e os Vereadores quando incorrerem em infrações político-administrativas; II - Compete à Mesa da Câmara promulgar a Lei Orgânica e suas Emendas; III - A Comissão de Ética Parlamentar é uma comissão permanente da Câmara.',
    'pergunta_2_alternativa_1':'Apenas I está correta',
    'pergunta_2_alternativa_2':'Apenas I e II estão corretas',
    'pergunta_2_alternativa_3':'Apenas I e III estão corretas',
    'pergunta_2_alternativa_4':'Todas estão corretas',
    'pergunta_2_resposta_correta':'Apenas I e III estão corretas',
    'pergunta_2_justificativa':'A promulgação da Lei Orgânica e suas Emendas é competência do Presidente da Câmara, não da Mesa Diretora como um todo.',

    'pergunta_3':'De acordo com o Regimento Interno da Câmara de Vereadores, é de competência específica da Comissão de Constituição, Justiça e Legislação da Câmara Municipal:',
    'pergunta_3_alternativa_1':'Opinar e dar parecer sobre as doações e indenizações do sistema viário, áreas verdes e demais áreas públicas',
    'pergunta_3_alternativa_2':'Elaborar a redação final dos Projetos das Leis Orçamentárias',
    'pergunta_3_alternativa_3':'Emitir parecer sobre todas as proposições em tramitação, bem como sobre substitutivos, emendas, subemendas e mensagens retificativas',
    'pergunta_3_alternativa_4':'Elaborar e propor ações preventivas visando à segurança e à proteção dos direitos humanos e do cidadão',
    'pergunta_3_resposta_correta':'Emitir parecer sobre todas as proposições em tramitação, bem como sobre substitutivos, emendas, subemendas e mensagens retificativas',
    'pergunta_3_justificativa':'A Comissão de Constituição, Justiça e Legislação tem como competência específica emitir parecer sobre a constitucionalidade e legalidade de todas as proposições em tramitação.',

    'pergunta_4':'Em conformidade com o Regimento Interno da Câmara de Vereadores, o Presidente da Câmara somente poderá votar nas seguintes hipóteses: I - Votação secreta; II - Quando houver empate em qualquer votação plenária; III - Quando a matéria exigir o voto favorável de 2/3 dos membros da Câmara.',
    'pergunta_4_alternativa_1':'Somente o item I',
    'pergunta_4_alternativa_2':'Somente os itens I e III',
    'pergunta_4_alternativa_3':'Somente os itens II e III',
    'pergunta_4_alternativa_4':'Todos os itens',
    'pergunta_4_resposta_correta':'Somente os itens II e III',
    'pergunta_4_justificativa':'O Presidente da Câmara vota apenas em caso de empate ou quando a matéria exigir o voto favorável de 2/3 dos membros da Casa.',

    'pergunta_5':'Em relação às Comissões Permanentes da Câmara de Vereadores, associe corretamente: (1) Comissão Permanente de Legislação Participativa e Comunitária; (2) Comissão de Desenvolvimento Urbano, Transporte e Habitação; (3) Comissão de Direitos Humanos, Cidadania e Segurança com suas competências: ( ) Promove estudos, pesquisas e investigações sobre problemas de interesse público relativos à sua competência; ( ) Acompanha e avalia os serviços de segurança urbana; ( ) Promove debates e estudos sobre problemas locais de interesse público e sugestões de iniciativa legislativa.',
    'pergunta_5_alternativa_1':'1 - 2 - 3',
    'pergunta_5_alternativa_2':'2 - 3 - 1',
    'pergunta_5_alternativa_3':'3 - 1 - 2',
    'pergunta_5_alternativa_4':'1 - 3 - 2',
    'pergunta_5_resposta_correta':'2 - 3 - 1',
    'pergunta_5_justificativa':'A Comissão de Desenvolvimento Urbano promove estudos sobre problemas de interesse público; a Comissão de Direitos Humanos acompanha a segurança urbana; e a Comissão de Legislação Participativa promove debates sobre problemas locais.',

    'pergunta_6':'De acordo com o Regimento Interno da Câmara Municipal de Caxias do Sul, assumirá a presidência da Sessão Solene de Instalação:',
    'pergunta_6_alternativa_1':'o Vereador mais idoso',
    'pergunta_6_alternativa_2':'o Vereador mais jovem',
    'pergunta_6_alternativa_3':'o Vereador mais votado',
    'pergunta_6_alternativa_4':'o Vereador mais articulado',
    'pergunta_6_resposta_correta':'o Vereador mais idoso',
    'pergunta_6_justificativa':'Conforme estabelece o Regimento Interno, na Sessão Solene de Instalação preside o Vereador mais idoso presente.',

    'pergunta_7':'Na Sessão Solene de Instalação na Câmara Municipal, obedecer-se-á à seguinte Ordem do Dia: I - apresentação dos diplomas eleitorais; II - prestação do compromisso legal; III - posse do Prefeito, do Vice-Prefeito e dos Vereadores presentes; IV - eleição e posse dos membros da Mesa Diretora; V - posse da Comissão Representativa e das Comissões Permanentes',
    'pergunta_7_alternativa_1':'se correta a I',
    'pergunta_7_alternativa_2':'se correta a I e II',
    'pergunta_7_alternativa_3':'se correta a I, II e III',
    'pergunta_7_alternativa_4':'se correta a I, II, III e IV',
    'pergunta_7_resposta_correta':'se correta a I, II, III e IV',
    'pergunta_7_justificativa':'A posse da Comissão Representativa e das Comissões Permanentes não ocorre na Sessão Solene de Instalação, mas posteriormente.',

    'pergunta_8':'A Câmara Municipal reunir-se-á anualmente, em sessão legislativa ordinária:',
    'pergunta_8_alternativa_1':'de 1º de janeiro a 22 de dezembro',
    'pergunta_8_alternativa_2':'de 15 de janeiro a 22 de dezembro',
    'pergunta_8_alternativa_3':'de 1º de fevereiro a 15 de dezembro',
    'pergunta_8_alternativa_4':'de 2 de fevereiro a 15 de dezembro',
    'pergunta_8_resposta_correta':'de 2 de fevereiro a 15 de dezembro',
    'pergunta_8_justificativa':'Conforme dispõe o Regimento Interno, o período anual de sessões legislativas ordinárias é de 2 de fevereiro a 15 de dezembro.',

    'pergunta_9':'As funções dos membros da Mesa Diretora somente cessarão: I – ao final do ano legislativo; II – pela renúncia apresentada por escrito; III – pela perda do mandato; IV – pela destituição do cargo; V – por morte',
    'pergunta_9_alternativa_1':'apenas a I',
    'pergunta_9_alternativa_2':'apenas a I e II',
    'pergunta_9_alternativa_3':'apenas a I, II e III',
    'pergunta_9_alternativa_4':'I, II, III, IV e V',
    'pergunta_9_resposta_correta':'I, II, III, IV e V',
    'pergunta_9_justificativa':'Todas as hipóteses listadas são formas de cessação das funções dos membros da Mesa Diretora, conforme previsto no Regimento Interno.',

    'pergunta_10':'Associe as comissões às suas classificações: I - Permanentes; II – Temporárias; ( ) Comissão de Desenvolvimento Urbano, Transporte e Habitação; ( ) Comissão de Agricultura, Agroindústria, Pecuária e Cooperativismo; ( ) Comissão de Inquérito; ( ) Comissão de Representação; ( ) Comissão de Legislação Participativa e Comunitária',
    'pergunta_10_alternativa_1':'I – II – I – II – I',
    'pergunta_10_alternativa_2':'I – I – II – II – I',
    'pergunta_10_alternativa_3':'I – I – I – I – II',
    'pergunta_10_alternativa_4':'II – II – II – I – I',
    'pergunta_10_resposta_correta':'I – I – II – II – I',
    'pergunta_10_justificativa':'As Comissões de Desenvolvimento Urbano, Agricultura e Legislação Participativa são permanentes, enquanto as de Inquérito e Representação são temporárias.',

    'pergunta_11':'O Vereador de Caxias do Sul pode licenciar-se, nos seguintes casos: I - por moléstia devidamente comprovada; II - para desempenhar missões temporárias de caráter cultural ou de interesse do Município; III - para tratar de interesses particulares por prazo determinado; IV – para assumir cargo na Administração Direta ou Indireta; V – para realizar cursos de formação na área pública',
    'pergunta_11_alternativa_1':'apenas a I',
    'pergunta_11_alternativa_2':'apenas a I e II',
    'pergunta_11_alternativa_3':'apenas a I, II e III',
    'pergunta_11_alternativa_4':'apenas a I, II, III e IV',
    'pergunta_11_resposta_correta':'apenas a I, II e III',
    'pergunta_11_justificativa':'O Regimento Interno não prevê licença para assumir cargos na administração pública nem para cursos de formação como causas de licenciamento.',

    'pergunta_12':'As Sessões da Câmara são: I - Solenes de Instalação; II - Ordinárias; III - Extraordinárias; IV – Solenes; V – Solenes de Encerramento',
    'pergunta_12_alternativa_1':'apenas a I',
    'pergunta_12_alternativa_2':'apenas a I e II',
    'pergunta_12_alternativa_3':'apenas a I, II e III',
    'pergunta_12_alternativa_4':'I, II, III, IV e V',
    'pergunta_12_resposta_correta':'I, II, III, IV e V',
    'pergunta_12_justificativa':'O Regimento Interno prevê todos esses tipos de sessões como integrantes do funcionamento da Câmara Municipal.',

    'pergunta_13':'As Sessões Ordinárias e Extraordinárias só poderão ser abertas com a presença de, no mínimo, ______________ dos membros da Câmara e terão a duração máxima de ______________',
    'pergunta_13_alternativa_1':'um quinto (1/5) – 1 hora',
    'pergunta_13_alternativa_2':'um quarto (1/4) – 2 horas',
    'pergunta_13_alternativa_3':'um terço (1/3) – 3 horas',
    'pergunta_13_alternativa_4':'a metade – 1 hora',
    'pergunta_13_resposta_correta':'um terço (1/3) – 3 horas',
    'pergunta_13_justificativa':'Conforme estabelece o Regimento Interno, o quorum para abertura é de 1/3 dos membros e a duração máxima é de 3 horas.',

    'pergunta_14':'Para a Tribuna Livre da segunda quinzena, poderão requerer a sua utilização as seguintes instituições: I – clubes de serviço; II – entidades beneficentes, culturais, desportivas, sociais, religiosas e classistas; III – fundações; IV – associações; V – poderes públicos constituídos no Município',
    'pergunta_14_alternativa_1':'apenas a I',
    'pergunta_14_alternativa_2':'apenas a I e II',
    'pergunta_14_alternativa_3':'apenas a I, II e III',
    'pergunta_14_alternativa_4':'I, II, III, IV e V',
    'pergunta_14_resposta_correta':'I, II, III, IV e V',
    'pergunta_14_justificativa':'Todas as instituições listadas podem requerer a utilização da Tribuna Livre na segunda quinzena, conforme previsto no Regimento.',

    'pergunta_15':'Em relação aos registros e revisões das sessões, pode-se afirmar que: I - Ao Presidente compete mandar suprir expressões que atentem contra o decoro parlamentar; II - É permitido ao Vereador fazer a revisão de seu pronunciamento até 10 dias úteis; III - O convocado terá 15 dias úteis para revisar seu pronunciamento; IV - As leituras efetuadas em Plenário deverão ser fornecidas ao Setor de Registros; V - Exposições de cartazes não serão registradas',
    'pergunta_15_alternativa_1':'apenas a I',
    'pergunta_15_alternativa_2':'apenas a II e III',
    'pergunta_15_alternativa_3':'apenas a I, IV e V',
    'pergunta_15_alternativa_4':'I, II, III, IV e V',
    'pergunta_15_resposta_correta':'I, II, III, IV e V',
    'pergunta_15_justificativa':'Todas as afirmativas estão corretas e em conformidade com as disposições regimentais sobre registros e revisões.',

    'pergunta_16':'Em relação ao controle externo das contas municipais, podemos afirmar que: I - As contas serão apresentadas até noventa dias do encerramento do exercício; II - Se não forem apresentadas, a Comissão de Fiscalização deverá fazê-lo em trinta dias; III - O contribuinte terá prazo de sessenta dias para questionar; IV - As contas serão enviadas ao Tribunal de Contas; V - A Comissão dará parecer em trinta dias',
    'pergunta_16_alternativa_1':'se correta a I',
    'pergunta_16_alternativa_2':'se correta a I e II',
    'pergunta_16_alternativa_3':'se correta a I, II e III',
    'pergunta_16_alternativa_4':'I, II, III, IV e V',
    'pergunta_16_resposta_correta':'I, II, III, IV e V',
    'pergunta_16_justificativa':'Todas as afirmativas estão em conformidade com o processo de prestação de contas estabelecido no Regimento Interno.',

    'pergunta_17':'De acordo com o Regimento Interno, são sessões que podem ser realizadas independentemente de quorum: I - Solenes; II - Extraordinárias; III - Ordinárias',
    'pergunta_17_alternativa_1':'Somente os itens I e II',
    'pergunta_17_alternativa_2':'Somente os itens I e III',
    'pergunta_17_alternativa_3':'Somente os itens II e III',
    'pergunta_17_alternativa_4':'Todos os itens',
    'pergunta_17_resposta_correta':'Somente os itens I e II',
    'pergunta_17_justificativa':'As sessões solenes e extraordinárias não dependem de quorum para sua realização, diferentemente das ordinárias.',

    'pergunta_18':'Considerando-se as definições apresentadas no Regimento Interno, marque a alternativa correta:',
    'pergunta_18_alternativa_1':'A Ordem do Dia constitui-se da matéria sobre a qual a Câmara tenha que se manifestar através de voto',
    'pergunta_18_alternativa_2':'Proposição é toda matéria sujeita à deliberação da Câmara',
    'pergunta_18_alternativa_3':'Projeto de Decreto Legislativo regula matéria de exclusiva competência da Câmara',
    'pergunta_18_alternativa_4':'Moção é a interrupção consentida do orador para indagação',
    'pergunta_18_resposta_correta':'Projeto de Decreto Legislativo regula matéria de exclusiva competência da Câmara',
    'pergunta_18_justificativa':'A primeira afirmativa está incompleta, a segunda é muito ampla, e a quarta descreve aparte, não moção. A terceira está correta conforme definição regimentai.',

    'pergunta_19':'De acordo com o Regimento Interno, a Comissão de Representação tem como função:',
    'pergunta_19_alternativa_1':'Representar a Câmara em eventos oficiais',
    'pergunta_19_alternativa_2':'Fiscalizar os atos do Poder Executivo',
    'pergunta_19_alternativa_3':'Elaborar pareceres sobre matérias legislativas',
    'pergunta_19_alternativa_4':'Coordenar as comissões temporárias',
    'pergunta_19_resposta_correta':'Representar a Câmara em eventos oficiais',
    'pergunta_19_justificativa':'A Comissão de Representação tem como competência específica representar a Câmara Municipal em solenidades e eventos oficiais.',

    'pergunta_20':'O Regimento Interno estabelece que as proposições devem ser protocolizadas:',
    'pergunta_20_alternativa_1':'Apenas pessoalmente pelo autor',
    'pergunta_20_alternativa_2':'Pelo autor ou procurador devidamente credenciado',
    'pergunta_20_alternativa_3':'Apenas pelo líder do partido',
    'pergunta_20_alternativa_4':'Por qualquer cidadão sem necessidade de identificação',
    'pergunta_20_resposta_correta':'Pelo autor ou procurador devidamente credenciado',
    'pergunta_20_justificativa':'O protocolo de proposições pode ser feito pelo próprio autor ou por procurador devidamente credenciado, conforme dispõe o Regimento Interno.',

    // Continuação das próximas 80 questões seguindo o mesmo padrão...
    'pergunta_21':'Conforme o Regimento Interno, o veto do Prefeito será apreciado pela Câmara no prazo de:',
    'pergunta_21_alternativa_1':'15 dias úteis',
    'pergunta_21_alternativa_2':'30 dias corridos',
    'pergunta_21_alternativa_3':'30 dias úteis',
    'pergunta_21_alternativa_4':'45 dias corridos',
    'pergunta_21_resposta_correta':'30 dias corridos',
    'pergunta_21_justificativa':'O Regimento Interno estabelece o prazo de 30 dias corridos para a apreciação do veto pelo Plenário da Câmara.',

 
    
    'pergunta_22':'De acordo com o Regimento Interno, a Comissão de Representação é composta por:',
    'pergunta_22_alternativa_1':'3 membros titulares e 3 suplentes',
    'pergunta_22_alternativa_2':'5 membros titulares e 5 suplentes',
    'pergunta_22_alternativa_3':'7 membros titulares e 7 suplentes',
    'pergunta_22_alternativa_4':'9 membros titulares e 9 suplentes',
    'pergunta_22_resposta_correta':'5 membros titulares e 5 suplentes',
    'pergunta_22_justificativa':'A Comissão de Representação é composta por 5 membros titulares e igual número de suplentes, conforme disposição regimentai.',

    'pergunta_23':'O Regimento Interno estabelece que o pedido de informação ao Prefeito Municipal deve ser:',
    'pergunta_23_alternativa_1':'aprovado pela maioria simples',
    'pergunta_23_alternativa_2':'aprovado por 2/3 dos vereadores',
    'pergunta_23_alternativa_3':'de iniciativa exclusiva do Presidente',
    'pergunta_23_alternativa_4':'aprovado pela Comissão de Justiça',
    'pergunta_23_resposta_correta':'aprovado pela maioria simples',
    'pergunta_23_justificativa':'O pedido de informação é aprovado por maioria simples dos presentes, desde que esteja de acordo com o regimento.',

    'pergunta_24':'Conforme o Regimento Interno, as comissões permanentes são instaladas:',
    'pergunta_24_alternativa_1':'no primeiro dia útil de cada ano',
    'pergunta_24_alternativa_2':'após a posse da Mesa Diretora',
    'pergunta_24_alternativa_3':'30 dias após a posse dos vereadores',
    'pergunta_24_alternativa_4':'após a eleição da Mesa Diretora',
    'pergunta_24_resposta_correta':'após a eleição da Mesa Diretora',
    'pergunta_24_justificativa':'As comissões permanentes são instaladas após a eleição e posse dos membros da Mesa Diretora.',

    'pergunta_25':'O Regimento Interno estabelece que o recesso parlamentar ocorre:',
    'pergunta_25_alternativa_1':'de 1º a 31 de janeiro',
    'pergunta_25_alternativa_2':'de 15 de dezembro a 15 de janeiro',
    'pergunta_25_alternativa_3':'de 23 de dezembro a 1º de fevereiro',
    'pergunta_25_alternativa_4':'de 20 de dezembro a 31 de janeiro',
    'pergunta_25_resposta_correta':'de 23 de dezembro a 1º de fevereiro',
    'pergunta_25_justificativa':'O recesso parlamentar estabelecido no Regimento Interno vai de 23 de dezembro a 1º de fevereiro.',

    'pergunta_26':'De acordo com o Regimento, a Comissão de Ética Parlamentar tem competência para:',
    'pergunta_26_alternativa_1':'apreciar denúncias contra o Prefeito',
    'pergunta_26_alternativa_2':'processar e julgar servidores públicos',
    'pergunta_26_alternativa_3':'apreciar representações sobre conduta de vereadores',
    'pergunta_26_alternativa_4':'fiscalizar as contas do Poder Executivo',
    'pergunta_26_resposta_correta':'apreciar representações sobre conduta de vereadores',
    'pergunta_26_justificativa':'Compete à Comissão de Ética apreciar representações sobre conduta de vereadores que violem o decoro parlamentar.',

    'pergunta_27':'O Regimento Interno estabelece que as sessões especiais destinam-se a:',
    'pergunta_27_alternativa_1':'debater vetos do Prefeito',
    'pergunta_27_alternativa_2':'homenagens e comemorações',
    'pergunta_27_alternativa_3':'apreciar projetos de lei complementar',
    'pergunta_27_alternativa_4':'discutir o orçamento municipal',
    'pergunta_27_resposta_correta':'homenagens e comemorações',
    'pergunta_27_justificativa':'As sessões especiais destinam-se a homenagens, comemorações cívicas e outros eventos de relevância pública.',

    'pergunta_28':'Conforme o Regimento, o prazo para sustação de proposição pelo autor é de:',
    'pergunta_28_alternativa_1':'até o início da discussão',
    'pergunta_28_alternativa_2':'até a votação em primeiro turno',
    'pergunta_28_alternativa_3':'até o envio às comissões',
    'pergunta_28_alternativa_4':'até a publicação em diário oficial',
    'pergunta_28_resposta_correta':'até o início da discussão',
    'pergunta_28_justificativa':'O autor pode sustar a proposição até o início da discussão em Plenário.',

    'pergunta_29':'De acordo com o Regimento Interno, a Mesa Diretora reúne-se:',
    'pergunta_29_alternativa_1':'semanalmente',
    'pergunta_29_alternativa_2':'quinzenalmente',
    'pergunta_29_alternativa_3':'mensalmente',
    'pergunta_29_alternativa_4':'bimestralmente',
    'pergunta_29_resposta_correta':'semanalmente',
    'pergunta_29_justificativa':'A Mesa Diretora reúne-se ordinariamente uma vez por semana, podendo realizar reuniões extraordinárias quando necessário.',

    'pergunta_30':'O Regimento estabelece que o aparte deve ser:',
    'pergunta_30_alternativa_1':'solicitado por escrito',
    'pergunta_30_alternativa_2':'concedido pelo Presidente',
    'pergunta_30_alternativa_3':'limitado a 3 minutos',
    'pergunta_30_alternativa_4':'apenas para vereadores da base',
    'pergunta_30_resposta_correta':'concedido pelo Presidente',
    'pergunta_30_justificativa':'O aparte depende de consentimento do orador e concessão do Presidente da sessão.',

    'pergunta_31':'Conforme o Regimento, as comissões temporárias têm prazo de:',
    'pergunta_31_alternativa_1':'60 dias, prorrogável uma vez',
    'pergunta_31_alternativa_2':'90 dias, prorrogável por igual período',
    'pergunta_31_alternativa_3':'120 dias, não prorrogável',
    'pergunta_31_alternativa_4':'180 dias, prorrogável por 90 dias',
    'pergunta_31_resposta_correta':'90 dias, prorrogável por igual período',
    'pergunta_31_justificativa':'As comissões temporárias têm prazo de 90 dias, podendo ser prorrogadas por igual período.',

    'pergunta_32':'De acordo com o Regimento, a ordem do dia é organizada:',
    'pergunta_32_alternativa_1':'pelo Presidente da Câmara',
    'pergunta_32_alternativa_2':'pela Mesa Diretora',
    'pergunta_32_alternativa_3':'pelos Líderes Partidários',
    'pergunta_32_alternativa_4':'pelo Chefe de Gabinete',
    'pergunta_32_resposta_correta':'pela Mesa Diretora',
    'pergunta_32_justificativa':'A ordem do dia é organizada pela Mesa Diretora, ouvidos os Líderes Partidários.',

    'pergunta_33':'O Regimento estabelece que as indicações ao Prefeito têm prazo de resposta de:',
    'pergunta_33_alternativa_1':'15 dias',
    'pergunta_33_alternativa_2':'30 dias',
    'pergunta_33_alternativa_3':'45 dias',
    'pergunta_33_alternativa_4':'60 dias',
    'pergunta_33_resposta_correta':'30 dias',
    'pergunta_33_justificativa':'As indicações ao Prefeito Municipal devem ser respondidas no prazo de 30 dias.',

    'pergunta_34':'Conforme o Regimento, a renúncia do mandato de vereador deve ser:',
    'pergunta_34_alternativa_1':'apresentada por escrito ao Presidente',
    'pergunta_34_alternativa_2':'aprovada pelo Plenário',
    'pergunta_34_alternativa_3':'publicada no diário oficial',
    'pergunta_34_alternativa_4':'todas as alternativas anteriores',
    'pergunta_34_resposta_correta':'todas as alternativas anteriores',
    'pergunta_34_justificativa':'A renúncia deve ser apresentada por escrito, aprovada pelo Plenário e publicada no diário oficial.',

    'pergunta_35':'De acordo com o Regimento, o número máximo de apartes por orador é:',
    'pergunta_35_alternativa_1':'2 apartes',
    'pergunta_35_alternativa_2':'3 apartes',
    'pergunta_35_alternativa_3':'4 apartes',
    'pergunta_35_alternativa_4':'5 apartes',
    'pergunta_35_resposta_correta':'3 apartes',
    'pergunta_35_justificativa':'Cada vereador pode apartear até 3 vezes o mesmo orador na mesma sessão.',

    'pergunta_36':'O Regimento estabelece que as sessões ordinárias ocorrem:',
    'pergunta_36_alternativa_1':'às segundas e quartas-feiras',
    'pergunta_36_alternativa_2':'às terças e quintas-feiras',
    'pergunta_36_alternativa_3':'às quartas e sextas-feiras',
    'pergunta_36_alternativa_4':'de segunda a sexta-feira',
    'pergunta_36_resposta_correta':'às terças e quintas-feiras',
    'pergunta_36_justificativa':'As sessões ordinárias são realizadas às terças e quintas-feiras, nos horários estabelecidos.',

    'pergunta_37':'Conforme o Regimento, a Comissão de Finanças e Orçamento tem competência para:',
    'pergunta_37_alternativa_1':'elaborar o orçamento municipal',
    'pergunta_37_alternativa_2':'executar a despesa pública',
    'pergunta_37_alternativa_3':'examinar as proposições sobre matéria financeira',
    'pergunta_37_alternativa_4':'fiscalizar servidores públicos',
    'pergunta_37_resposta_correta':'examinar as proposições sobre matéria financeira',
    'pergunta_37_justificativa':'Compete à Comissão examinar as proposições sobre matéria financeira, orçamentária e fiscal.',

    'pergunta_38':'De acordo com o Regimento, o requerimento de urgência pode ser solicitado:',
    'pergunta_38_alternativa_1':'pelo autor da proposição',
    'pergunta_38_alternativa_2':'pelo Presidente da Câmara',
    'pergunta_38_alternativa_3':'pelos Líderes Partidários',
    'pergunta_38_alternativa_4':'todas as alternativas anteriores',
    'pergunta_38_resposta_correta':'todas as alternativas anteriores',
    'pergunta_38_justificativa':'O requerimento de urgência pode ser solicitado pelo autor, Presidente ou Líderes Partidários.',

    'pergunta_39':'O Regimento estabelece que o voto secreto é obrigatório para:',
    'pergunta_39_alternativa_1':'projetos de lei ordinária',
    'pergunta_39_alternativa_2':'eleição da Mesa Diretora',
    'pergunta_39_alternativa_3':'aprovação de indicações',
    'pergunta_39_alternativa_4':'todas as votações',
    'pergunta_39_resposta_correta':'eleição da Mesa Diretora',
    'pergunta_39_justificativa':'O voto secreto é obrigatório para eleição da Mesa Diretora e em casos de perda de mandato.',

    'pergunta_40':'Conforme o Regimento, a tribuna livre tem duração máxima de:',
    'pergunta_40_alternativa_1':'10 minutos por expositor',
    'pergunta_40_alternativa_2':'15 minutos por expositor',
    'pergunta_40_alternativa_3':'20 minutos por expositor',
    'pergunta_40_alternativa_4':'30 minutos por expositor',
    'pergunta_40_resposta_correta':'15 minutos por expositor',
    'pergunta_40_justificativa':'Cada expositor na tribuna livre tem direito a 15 minutos, não podendo ultrapassar este limite.',

    'pergunta_41':'De acordo com o Regimento, as comissões permanentes devem ter:',
    'pergunta_41_alternativa_1':'5 membros titulares',
    'pergunta_41_alternativa_2':'7 membros titulares',
    'pergunta_41_alternativa_3':'9 membros titulares',
    'pergunta_41_alternativa_4':'11 membros titulares',
    'pergunta_41_resposta_correta':'7 membros titulares',
    'pergunta_41_justificativa':'As comissões permanentes são compostas por 7 membros titulares e igual número de suplentes.',

    'pergunta_42':'O Regimento estabelece que o pedido de vistas em comissão tem prazo de:',
    'pergunta_42_alternativa_1':'3 dias úteis',
    'pergunta_42_alternativa_2':'5 dias úteis',
    'pergunta_42_alternativa_3':'7 dias úteis',
    'pergunta_42_alternativa_4':'10 dias úteis',
    'pergunta_42_resposta_correta':'5 dias úteis',
    'pergunta_42_justificativa':'O pedido de vistas em comissão tem prazo de 5 dias úteis para devolução do processo.',

    'pergunta_43':'Conforme o Regimento, a convocação extraordinária do Prefeito pode ser feita:',
    'pergunta_43_alternativa_1':'pelo Presidente da Câmara',
    'pergunta_43_alternativa_2':'pela maioria absoluta dos vereadores',
    'pergunta_43_alternativa_3':'pelos Líderes Partidários',
    'pergunta_43_alternativa_4':'pela Mesa Diretora',
    'pergunta_43_resposta_correta':'pela maioria absoluta dos vereadores',
    'pergunta_43_justificativa':'A convocação extraordinária do Prefeito depende de requerimento aprovado pela maioria absoluta dos vereadores.',

    'pergunta_44':'De acordo com o Regimento, o recurso contra decisão do Presidente deve ser:',
    'pergunta_44_alternativa_1':'apresentado por escrito',
    'pergunta_44_alternativa_2':'submetido ao Plenário',
    'pergunta_44_alternativa_3':'apreciado na mesma sessão',
    'pergunta_44_alternativa_4':'todas as alternativas anteriores',
    'pergunta_44_resposta_correta':'todas as alternativas anteriores',
    'pergunta_44_justificativa':'O recurso deve ser por escrito, submetido ao Plenário e apreciado na mesma sessão.',

    'pergunta_45':'O Regimento estabelece que as emendas ao projeto de lei orçamentária devem:',
    'pergunta_45_alternativa_1':'indicar a fonte de recursos',
    'pergunta_45_alternativa_2':'ser compatíveis com o plano plurianual',
    'pergunta_45_alternativa_3':'ser apresentadas em comissão',
    'pergunta_45_alternativa_4':'todas as alternativas anteriores',
    'pergunta_45_resposta_correta':'todas as alternativas anteriores',
    'pergunta_45_justificativa':'As emendas devem atender a todos os requisitos formais estabelecidos na legislação.',

    'pergunta_46':'Conforme o Regimento, a perda do mandato do vereador ocorre por:',
    'pergunta_46_alternativa_1':'ausência injustificada a 10 sessões consecutivas',
    'pergunta_46_alternativa_2':'ausência a 15 sessões no semestre',
    'pergunta_46_alternativa_3':'violação do decoro parlamentar',
    'pergunta_46_alternativa_4':'todas as alternativas anteriores',
    'pergunta_46_resposta_correta':'todas as alternativas anteriores',
    'pergunta_46_justificativa':'A perda do mandato pode ocorrer por quaisquer dessas hipóteses, conforme regimento e legislação.',

    'pergunta_47':'De acordo com o Regimento, a Comissão de Serviços Públicos tem competência para:',
    'pergunta_47_alternativa_1':'fiscalizar concessionárias de serviços',
    'pergunta_47_alternativa_2':'examinar projetos sobre transporte',
    'pergunta_47_alternativa_3':'apreciar matérias sobre saneamento',
    'pergunta_47_alternativa_4':'todas as alternativas anteriores',
    'pergunta_47_resposta_correta':'todas as alternativas anteriores',
    'pergunta_47_justificativa':'A Comissão de Serviços Públicos examina matérias relacionadas a todos os serviços públicos municipais.',

    'pergunta_48':'O Regimento estabelece que o prazo para emendas aos projetos é de:',
    'pergunta_48_alternativa_1':'5 dias úteis',
    'pergunta_48_alternativa_2':'7 dias úteis',
    'pergunta_48_alternativa_3':'10 dias úteis',
    'pergunta_48_alternativa_4':'15 dias úteis',
    'pergunta_48_resposta_correta':'5 dias úteis',
    'pergunta_48_justificativa':'O prazo para apresentação de emendas é de 5 dias úteis a partir da distribuição do processo.',

    'pergunta_49':'Conforme o Regimento, as sessões solenes são convocadas:',
    'pergunta_49_alternativa_1':'pelo Presidente da Câmara',
    'pergunta_49_alternativa_2':'pela Mesa Diretora',
    'pergunta_49_alternativa_3':'pelos Líderes Partidários',
    'pergunta_49_alternativa_4':'pelo Prefeito Municipal',
    'pergunta_49_resposta_correta':'pela Mesa Diretora',
    'pergunta_49_justificativa':'As sessões solenes são convocadas pela Mesa Diretora, por iniciativa própria ou mediante requerimento.',

    'pergunta_50':'De acordo com o Regimento, o registro de liderança partidária deve ser:',
    'pergunta_50_alternativa_1':'apresentado por escrito',
    'pergunta_50_alternativa_2':'assinado pelos filiados',
    'pergunta_50_alternativa_3':'comprovada a representatividade',
    'pergunta_50_alternativa_4':'todas as alternativas anteriores',
    'pergunta_50_resposta_correta':'todas as alternativas anteriores',
    'pergunta_50_justificativa':'O registro de liderança exige o cumprimento de todos os requisitos formais estabelecidos.',

    'pergunta_51':'O Regimento estabelece que a ordem do dia deve ser distribuída:',
    'pergunta_51_alternativa_1':'com 24 horas de antecedência',
    'pergunta_51_alternativa_2':'com 48 horas de antecedência',
    'pergunta_51_alternativa_3':'no início da sessão',
    'pergunta_51_alternativa_4':'na véspera da sessão',
    'pergunta_51_resposta_correta':'com 48 horas de antecedência',
    'pergunta_51_justificativa':'A ordem do dia deve ser distribuída com 48 horas de antecedência das sessões ordinárias.',

    'pergunta_52':'Conforme o Regimento, a Comissão de Educação e Cultura examina:',
    'pergunta_52_alternativa_1':'projetos sobre ensino municipal',
    'pergunta_52_alternativa_2':'matérias sobre atividades culturais',
    'pergunta_52_alternativa_3':'assuntos sobre esporte e lazer',
    'pergunta_52_alternativa_4':'todas as alternativas anteriores',
    'pergunta_52_resposta_correta':'todas as alternativas anteriores',
    'pergunta_52_justificativa':'A Comissão examina todas as matérias relacionadas à educação, cultura, esporte e lazer.',

    'pergunta_53':'De acordo com o Regimento, o pedido de informação deve conter:',
    'pergunta_53_alternativa_1':'fundamentação clara',
    'pergunta_53_alternativa_2':'identificação do requerente',
    'pergunta_53_alternativa_3':'clareza nas perguntas',
    'pergunta_53_alternativa_4':'todas as alternativas anteriores',
    'pergunta_53_resposta_correta':'todas as alternativas anteriores',
    'pergunta_53_justificativa':'O pedido de informação deve atender a todos os requisitos formais estabelecidos no regimento.',

    'pergunta_54':'O Regimento estabelece que as comissões podem realizar:',
    'pergunta_54_alternativa_1':'audiências públicas',
    'pergunta_54_alternativa_2':'reuniões conjuntas',
    'pergunta_54_alternativa_3':'diligências externas',
    'pergunta_54_alternativa_4':'todas as alternativas anteriores',
    'pergunta_54_resposta_correta':'todas as alternativas anteriores',
    'pergunta_54_justificativa':'As comissões têm competência para realizar todas essas atividades no exercício de suas funções.',

    'pergunta_55':'Conforme o Regimento, a posse do suplente ocorre:',
    'pergunta_55_alternativa_1':'após comprovação de vacância',
    'pergunta_55_alternativa_2':'mediante diplomação pelo TRE',
    'pergunta_55_alternativa_3':'após declaração de vaga',
    'pergunta_55_alternativa_4':'todas as alternativas anteriores',
    'pergunta_55_resposta_correta':'todas as alternativas anteriores',
    'pergunta_55_justificativa':'A posse do suplente depende do cumprimento de todos os requisitos legais e regimentais.',

    'pergunta_56':'De acordo com o Regimento, o prazo para resposta de requerimentos é:',
    'pergunta_56_alternativa_1':'15 dias',
    'pergunta_56_alternativa_2':'30 dias',
    'pergunta_56_alternativa_3':'45 dias',
    'pergunta_56_alternativa_4':'60 dias',
    'pergunta_56_resposta_correta':'30 dias',
    'pergunta_56_justificativa':'Os requerimentos de informação devem ser respondidos no prazo máximo de 30 dias.',

    'pergunta_57':'O Regimento estabelece que as votações nominais são:',
    'pergunta_57_alternativa_1':'realizadas por chamada nominal',
    'pergunta_57_alternativa_2':'registradas em ata',
    'pergunta_57_alternativa_3':'obrigatórias para matérias importantes',
    'pergunta_57_alternativa_4':'todas as alternativas anteriores',
    'pergunta_57_resposta_correta':'todas as alternativas anteriores',
    'pergunta_57_justificativa':'As votações nominais atendem a todos esses requisitos estabelecidos no regimento.',

    'pergunta_58':'Conforme o Regimento, a Comissão de Saúde examina:',
    'pergunta_58_alternativa_1':'projetos sobre assistência médica',
    'pergunta_58_alternativa_2':'matérias sobre saneamento básico',
    'pergunta_58_alternativa_3':'assuntos sobre vigilância sanitária',
    'pergunta_58_alternativa_4':'todas as alternativas anteriores',
    'pergunta_58_resposta_correta':'todas as alternativas anteriores',
    'pergunta_58_justificativa':'A Comissão de Saúde examina todas as matérias relacionadas à saúde pública municipal.',

    'pergunta_59':'De acordo com o Regimento, o vereador tem direito a:',
    'pergunta_59_alternativa_1':'uso da palavra',
    'pergunta_59_alternativa_2':'apresentação de proposições',
    'pergunta_59_alternativa_3':'acesso a informações',
    'pergunta_59_alternativa_4':'todas as alternativas anteriores',
    'pergunta_59_resposta_correta':'todas as alternativas anteriores',
    'pergunta_59_justificativa':'São direitos do vereador todos os listados, conforme estabelece o regimento interno.',

    'pergunta_60':'O Regimento estabelece que as sessões podem ser:',
    'pergunta_60_alternativa_1':'adiadas por falta de quorum',
    'pergunta_60_alternativa_2':'interrompidas por distúrbios',
    'pergunta_60_alternativa_3':'suspensas por acordo',
    'pergunta_60_alternativa_4':'todas as alternativas anteriores',
    'pergunta_60_resposta_correta':'todas as alternativas anteriores',
    'pergunta_60_justificativa':'O regimento prevê todas essas hipóteses para alteração do andamento das sessões.',

    'pergunta_61':'Conforme o Regimento, a Mesa Diretora deve zelar:',
    'pergunta_61_alternativa_1':'pelo patrimônio da Câmara',
    'pergunta_61_alternativa_2':'pela ordem nas sessões',
    'pergunta_61_alternativa_3':'pelo cumprimento do regimento',
    'pergunta_61_alternativa_4':'todas as alternativas anteriores',
    'pergunta_61_resposta_correta':'todas as alternativas anteriores',
    'pergunta_61_justificativa':'São atribuições da Mesa Diretora todas as mencionadas no regimento.',

    'pergunta_62':'De acordo com o Regimento, as comissões especiais são criadas para:',
    'pergunta_62_alternativa_1':'estudar assunto específico',
    'pergunta_62_alternativa_2':'elaborar parecer técnico',
    'pergunta_62_alternativa_3':'apreciar matéria complexa',
    'pergunta_62_alternativa_4':'todas as alternativas anteriores',
    'pergunta_62_resposta_correta':'todas as alternativas anteriores',
    'pergunta_62_justificativa':'As comissões especiais podem ser criadas para qualquer dessas finalidades.',

    'pergunta_63':'O Regimento estabelece que o Presidente da Câmara representa:',
    'pergunta_63_alternativa_1':'o Poder Legislativo',
    'pergunta_63_alternativa_2':'a Mesa Diretora',
    'pergunta_63_alternativa_3':'a Câmara Municipal',
    'pergunta_63_alternativa_4':'todas as alternativas anteriores',
    'pergunta_63_resposta_correta':'todas as alternativas anteriores',
    'pergunta_63_justificativa':'O Presidente representa a Câmara em todas as situações previstas no regimento.',

    'pergunta_64':'Conforme o Regimento, as decisões da Mesa Diretora são:',
    'pergunta_64_alternativa_1':'tomadas por maioria de votos',
    'pergunta_64_alternativa_2':'registradas em ata',
    'pergunta_64_alternativa_3':'divulgadas aos vereadores',
    'pergunta_64_alternativa_4':'todas as alternativas anteriores',
    'pergunta_64_resposta_correta':'todas as alternativas anteriores',
    'pergunta_64_justificativa':'Todas as alternativas correspondem a exigências regimentais para decisões da Mesa.',

    'pergunta_65':'De acordo com o Regimento, a Comissão de Justiça emite parecer sobre:',
    'pergunta_65_alternativa_1':'constitucionalidade',
    'pergunta_65_alternativa_2':'legalidade',
    'pergunta_65_alternativa_3':'regimentalidade',
    'pergunta_65_alternativa_4':'todas as alternativas anteriores',
    'pergunta_65_resposta_correta':'todas as alternativas anteriores',
    'pergunta_65_justificativa':'A Comissão de Justiça examina todos esses aspectos das proposições.',

    'pergunta_66':'O Regimento estabelece que as emendas devem ser:',
    'pergunta_66_alternativa_1':'compatíveis com a matéria',
    'pergunta_66_alternativa_2':'apresentadas em tempo hábil',
    'pergunta_66_alternativa_3':'subscritas pelo autor',
    'pergunta_66_alternativa_4':'todas as alternativas anteriores',
    'pergunta_66_resposta_correta':'todas as alternativas anteriores',
    'pergunta_66_justificativa':'As emendas devem atender a todos esses requisitos formais.',

    'pergunta_67':'Conforme o Regimento, os prazos processuais:',
    'pergunta_67_alternativa_1':'correm em dias úteis',
    'pergunta_67_alternativa_2':'excluem sábados e domingos',
    'pergunta_67_alternativa_3':'suspensos em recesso',
    'pergunta_67_alternativa_4':'todas as alternativas anteriores',
    'pergunta_67_resposta_correta':'todas as alternativas anteriores',
    'pergunta_67_justificativa':'Os prazos processuais obedecem a todas essas regras de contagem.',

    'pergunta_68':'De acordo com o Regimento, a tribuna é:',
    'pergunta_68_alternativa_1':'local de manifestação',
    'pergunta_68_alternativa_2':'espaço para debates',
    'pergunta_68_alternativa_3':'instrumento de fiscalização',
    'pergunta_68_alternativa_4':'todas as alternativas anteriores',
    'pergunta_68_resposta_correta':'todas as alternativas anteriores',
    'pergunta_68_justificativa':'A tribuna serve a todos esses propósitos no exercício do mandato.',

    'pergunta_69':'O Regimento estabelece que as sessões secretas:',
    'pergunta_69_alternativa_1':'são convocadas por decisão da maioria',
    'pergunta_69_alternativa_2':'têm discussão reservada',
    'pergunta_69_alternativa_3':'registram apenas a decisão final',
    'pergunta_69_alternativa_4':'todas as alternativas anteriores',
    'pergunta_69_resposta_correta':'todas as alternativas anteriores',
    'pergunta_69_justificativa':'As sessões secretas obedecem a todas essas regras especiais.',

    'pergunta_70':'Conforme o Regimento, os vereadores devem:',
    'pergunta_70_alternativa_1':'respeitar o regimento',
    'pergunta_70_alternativa_2':'manter decoro parlamentar',
    'pergunta_70_alternativa_3':'comparecer às sessões',
    'pergunta_70_alternativa_4':'todas as alternativas anteriores',
    'pergunta_70_resposta_correta':'todas as alternativas anteriores',
    'pergunta_70_justificativa':'São deveres dos vereadores todos os mencionados no regimento.',

    'pergunta_71':'De acordo com o Regimento, as comissões permanentes:',
    'pergunta_71_alternativa_1':'têm competência definida',
    'pergunta_71_alternativa_2':'são eleitas pelo Plenário',
    'pergunta_71_alternativa_3':'elaboram pareceres técnicos',
    'pergunta_71_alternativa_4':'todas as alternativas anteriores',
    'pergunta_71_resposta_correta':'todas as alternativas anteriores',
    'pergunta_71_justificativa':'Todas as características mencionadas são próprias das comissões permanentes.',

    'pergunta_72':'O Regimento estabelece que o quórum de deliberação é:',
    'pergunta_72_alternativa_1':'maioria dos presentes',
    'pergunta_72_alternativa_2':'desde que haja quórum de instalação',
    'pergunta_72_alternativa_3':'salvo casos de maioria qualificada',
    'pergunta_72_alternativa_4':'todas as alternativas anteriores',
    'pergunta_72_resposta_correta':'todas as alternativas anteriores',
    'pergunta_72_justificativa':'Todas as regras mencionadas se aplicam ao quórum de deliberação.',

    'pergunta_73':'Conforme o Regimento, as proposições devem conter:',
    'pergunta_73_alternativa_1':'fundamentação jurídica',
    'pergunta_73_alternativa_2':'exposição de motivos',
    'pergunta_73_alternativa_3':'clareza na redação',
    'pergunta_73_alternativa_4':'todas as alternativas anteriores',
    'pergunta_73_resposta_correta':'todas as alternativas anteriores',
    'pergunta_73_justificativa':'Todas essas exigências formais devem ser observadas nas proposições.',

    'pergunta_74':'De acordo com o Regimento, a Comissão de Economia examina:',
    'pergunta_74_alternativa_1':'projetos sobre desenvolvimento',
    'pergunta_74_alternativa_2':'matérias sobre comércio',
    'pergunta_74_alternativa_3':'assuntos sobre indústria',
    'pergunta_74_alternativa_4':'todas as alternativas anteriores',
    'pergunta_74_resposta_correta':'todas as alternativas anteriores',
    'pergunta_74_justificativa':'A Comissão examina todas as matérias relacionadas ao desenvolvimento econômico.',

    'pergunta_75':'O Regimento estabelece que as audiências públicas:',
    'pergunta_75_alternativa_1':'são convocadas por comissões',
    'pergunta_75_alternativa_2':'têm caráter informativo',
    'pergunta_75_alternativa_3':'permitem participação popular',
    'pergunta_75_alternativa_4':'todas as alternativas anteriores',
    'pergunta_75_resposta_correta':'todas as alternativas anteriores',
    'pergunta_75_justificativa':'As audiências públicas atendem a todas essas finalidades.',

    'pergunta_76':'Conforme o Regimento, os recursos hierárquicos:',
    'pergunta_76_alternativa_1':'são interpostos ao Presidente',
    'pergunta_76_alternativa_2':'decididos pelo Plenário',
    'pergunta_76_alternativa_3':'têm efeito suspensivo',
    'pergunta_76_alternativa_4':'todas as alternativas anteriores',
    'pergunta_76_resposta_correta':'todas as alternativas anteriores',
    'pergunta_76_justificativa':'Os recursos obedecem a todas essas regras regimentais.',

    'pergunta_77':'De acordo com o Regimento, a Comissão de Obras examina:',
    'pergunta_77_alternativa_1':'projetos de construção',
    'pergunta_77_alternativa_2':'matérias sobre urbanismo',
    'pergunta_77_alternativa_3':'assuntos sobre infraestrutura',
    'pergunta_77_alternativa_4':'todas as alternativas anteriores',
    'pergunta_77_resposta_correta':'todas as alternativas anteriores',
    'pergunta_77_justificativa':'A Comissão examina todas as matérias relacionadas a obras públicas.',

    'pergunta_78':'O Regimento estabelece que as sessões conjuntas:',
    'pergunta_78_alternativa_1':'requerem aprovação prévia',
    'pergunta_78_alternativa_2':'seguem regras especiais',
    'pergunta_78_alternativa_3':'são presididas pelo mais antigo',
    'pergunta_78_alternativa_4':'todas as alternativas anteriores',
    'pergunta_78_resposta_correta':'todas as alternativas anteriores',
    'pergunta_78_justificativa':'As sessões conjuntas obedecem a todas essas regras especiais.',

    'pergunta_79':'Conforme o Regimento, os vereadores têm imunidade:',
    'pergunta_79_alternativa_1':'parlamentar',
    'pergunta_79_alternativa_2':'material',
    'pergunta_79_alternativa_3':'processual',
    'pergunta_79_alternativa_4':'todas as alternativas anteriores',
    'pergunta_79_resposta_correta':'todas as alternativas anteriores',
    'pergunta_79_justificativa':'Os vereadores gozam de todos esses tipos de imunidade previstos na lei.',

    'pergunta_80':'De acordo com o Regimento, a Comissão de Agricultura examina:',
    'pergunta_80_alternativa_1':'projetos sobre produção rural',
    'pergunta_80_alternativa_2':'matérias sobre agroindústria',
    'pergunta_80_alternativa_3':'assuntos sobre pecuária',
    'pergunta_80_alternativa_4':'todas as alternativas anteriores',
    'pergunta_80_resposta_correta':'todas as alternativas anteriores',
    'pergunta_80_justificativa':'A Comissão examina todas as matérias relacionadas ao setor agropecuário.',

    'pergunta_81':'O Regimento estabelece que as moções são:',
    'pergunta_81_alternativa_1':'manifestações de vontade',
    'pergunta_81_alternativa_2':'aprovadas por maioria',
    'pergunta_81_alternativa_3':'registradas em ata',
    'pergunta_81_alternativa_4':'todas as alternativas anteriores',
    'pergunta_81_resposta_correta':'todas as alternativas anteriores',
    'pergunta_81_justificativa':'As moções possuem todas essas características regimentais.',

    'pergunta_82':'Conforme o Regimento, os prazos para emendas:',
    'pergunta_82_alternativa_1':'são improrrogáveis',
    'pergunta_82_alternativa_2':'correm em dias úteis',
    'pergunta_82_alternativa_3':'iniciam da publicação',
    'pergunta_82_alternativa_4':'todas as alternativas anteriores',
    'pergunta_82_resposta_correta':'todas as alternativas anteriores',
    'pergunta_82_justificativa':'Todos esses aspectos são observados nos prazos para emendas.',

    'pergunta_83':'De acordo com o Regimento, a Comissão de Turismo examina:',
    'pergunta_83_alternativa_1':'projetos sobre hotelaria',
    'pergunta_83_alternativa_2':'matérias sobre eventos',
    'pergunta_83_alternativa_3':'assuntos sobre lazer',
    'pergunta_83_alternativa_4':'todas as alternativas anteriores',
    'pergunta_83_resposta_correta':'todas as alternativas anteriores',
    'pergunta_83_justificativa':'A Comissão examina todas as matérias relacionadas ao turismo municipal.',

    'pergunta_84':'O Regimento estabelece que as indicações:',
    'pergunta_84_alternativa_1':'são sugestões ao Executivo',
    'pergunta_84_alternativa_2':'não têm caráter vinculante',
    'pergunta_84_alternativa_3':'devem ser fundamentadas',
    'pergunta_84_alternativa_4':'todas as alternativas anteriores',
    'pergunta_84_resposta_correta':'todas as alternativas anteriores',
    'pergunta_84_justificativa':'As indicações possuem todas essas características regimentais.',

    'pergunta_85':'Conforme o Regimento, os projetos de resolução:',
    'pergunta_85_alternativa_1':'regulam matéria interna',
    'pergunta_85_alternativa_2':'são aprovados por maioria',
    'pergunta_85_alternativa_3':'não exigem sanção',
    'pergunta_85_alternativa_4':'todas as alternativas anteriores',
    'pergunta_85_resposta_correta':'todas as alternativas anteriores',
    'pergunta_85_justificativa':'Os projetos de resolução atendem a todas essas características.',

    'pergunta_86':'De acordo com o Regimento, a Comissão de Meio Ambiente examina:',
    'pergunta_86_alternativa_1':'projetos sobre ecologia',
    'pergunta_86_alternativa_2':'matérias sobre poluição',
    'pergunta_86_alternativa_3':'assuntos sobre recursos naturais',
    'pergunta_86_alternativa_4':'todas as alternativas anteriores',
    'pergunta_86_resposta_correta':'todas as alternativas anteriores',
    'pergunta_86_justificativa':'A Comissão examina todas as matérias ambientais de competência municipal.',

    'pergunta_87':'O Regimento estabelece que os decretos legislativos:',
    'pergunta_87_alternativa_1':'são atos administrativos',
    'pergunta_87_alternativa_2':'não exigem sanção',
    'pergunta_87_alternativa_3':'têm eficácia interna',
    'pergunta_87_alternativa_4':'todas as alternativas anteriores',
    'pergunta_87_resposta_correta':'todas as alternativas anteriores',
    'pergunta_87_justificativa':'Os decretos legislativos possuem todas essas características.',

    'pergunta_88':'Conforme o Regimento, as súmulas são:',
    'pergunta_88_alternativa_1':'decisões reiteradas',
    'pergunta_88_alternativa_2':'editadas pela Mesa',
    'pergunta_88_alternativa_3':'vinculantes para servidores',
    'pergunta_88_alternativa_4':'todas as alternativas anteriores',
    'pergunta_88_resposta_correta':'todas as alternativas anteriores',
    'pergunta_88_justificativa':'As súmulas possuem todas essas características regimentais.',

    'pergunta_89':'De acordo com o Regimento, a Comissão de Direitos Humanos:',
    'pergunta_89_alternativa_1':'examina denúncias',
    'pergunta_89_alternativa_2':'promove estudos',
    'pergunta_89_alternativa_3':'fiscaliza direitos',
    'pergunta_89_alternativa_4':'todas as alternativas anteriores',
    'pergunta_89_resposta_correta':'todas as alternativas anteriores',
    'pergunta_89_justificativa':'A Comissão tem competência para todas essas atividades.',

    'pergunta_90':'O Regimento estabelece que as sessões de debate:',
    'pergunta_90_alternativa_1':'têm tema específico',
    'pergunta_90_alternativa_2':'convidados externos',
    'pergunta_90_alternativa_3':'tempo limitado',
    'pergunta_90_alternativa_4':'todas as alternativas anteriores',
    'pergunta_90_resposta_correta':'todas as alternativas anteriores',
    'pergunta_90_justificativa':'As sessões de debate obedecem a todas essas regras.',

    'pergunta_91':'Conforme o Regimento, os projetos de lei complementar:',
    'pergunta_91_alternativa_1':'exigem maioria absoluta',
    'pergunta_91_alternativa_2':'tratam de matéria reservada',
    'pergunta_91_alternativa_3':'seguem tramitação especial',
    'pergunta_91_alternativa_4':'todas as alternativas anteriores',
    'pergunta_91_resposta_correta':'todas as alternativas anteriores',
    'pergunta_91_justificativa':'Os projetos de lei complementar atendem a todas essas exigências.',

    'pergunta_92':'De acordo com o Regimento, a Comissão de Segurança:',
    'pergunta_92_alternativa_1':'examina políticas públicas',
    'pergunta_92_alternativa_2':'fiscaliza órgãos de segurança',
    'pergunta_92_alternativa_3':'promove estudos',
    'pergunta_92_alternativa_4':'todas as alternativas anteriores',
    'pergunta_92_resposta_correta':'todas as alternativas anteriores',
    'pergunta_92_justificativa':'A Comissão tem competência para todas essas atribuições.',

    'pergunta_93':'O Regimento estabelece que as emendas ao orçamento:',
    'pergunta_93_alternativa_1':'devem ser compatíveis',
    'pergunta_93_alternativa_2':'indicar fonte de recursos',
    'pergunta_93_alternativa_3':'apresentadas em comissão',
    'pergunta_93_alternativa_4':'todas as alternativas anteriores',
    'pergunta_93_resposta_correta':'todas as alternativas anteriores',
    'pergunta_93_justificativa':'As emendas orçamentárias devem atender a todos esses requisitos.',

    'pergunta_94':'Conforme o Regimento, os requerimentos de urgência:',
    'pergunta_94_alternativa_1':'são apreciados em 24 horas',
    'pergunta_94_alternativa_2':'exigem justificativa',
    'pergunta_94_alternativa_3':'tramitam em regime especial',
    'pergunta_94_alternativa_4':'todas as alternativas anteriores',
    'pergunta_94_resposta_correta':'todas as alternativas anteriores',
    'pergunta_94_justificativa':'Os requerimentos de urgência obedecem a todas essas regras.',

    'pergunta_95':'De acordo com o Regimento, a Comissão de Ética:',
    'pergunta_95_alternativa_1':'examina conduta parlamentar',
    'pergunta_95_alternativa_2':'aplica sanções disciplinares',
    'pergunta_95_alternativa_3':'emite pareceres',
    'pergunta_95_alternativa_4':'todas as alternativas anteriores',
    'pergunta_95_resposta_correta':'todas as alternativas anteriores',
    'pergunta_95_justificativa':'A Comissão de Ética tem competência para todas essas atividades.',

    'pergunta_96':'O Regimento estabelece que as leis delegadas:',
    'pergunta_96_alternativa_1':'exigem autorização legislativa',
    'pergunta_96_alternativa_2':'têm limites definidos',
    'pergunta_96_alternativa_3':'são editadas pelo Prefeito',
    'pergunta_96_alternativa_4':'todas as alternativas anteriores',
    'pergunta_96_resposta_correta':'todas as alternativas anteriores',
    'pergunta_96_justificativa':'As leis delegadas atendem a todas essas características.',

    'pergunta_97':'Conforme o Regimento, os projetos de lei ordinária:',
    'pergunta_97_alternativa_1':'tramitam em comissões',
    'pergunta_97_alternativa_2':'exigem maioria simples',
    'pergunta_97_alternativa_3':'são sancionados pelo Prefeito',
    'pergunta_97_alternativa_4':'todas as alternativas anteriores',
    'pergunta_97_resposta_correta':'todas as alternativas anteriores',
    'pergunta_97_justificativa':'Os projetos de lei ordinária seguem todas essas regras de tramitação.',

    'pergunta_98':'De acordo com o Regimento, a Comissão de Fiscalização:',
    'pergunta_98_alternativa_1':'examina contas públicas',
    'pergunta_98_alternativa_2':'fiscaliza contratos',
    'pergunta_98_alternativa_3':'acompanha licitações',
    'pergunta_98_alternativa_4':'todas as alternativas anteriores',
    'pergunta_98_resposta_correta':'todas as alternativas anteriores',
    'pergunta_98_justificativa':'A Comissão tem competência para todas essas atividades fiscalizatórias.',

    'pergunta_99':'O Regimento estabelece que as sessões extraordinárias:',
    'pergunta_99_alternativa_1':'são convocadas pelo Presidente',
    'pergunta_99_alternativa_2':'tratam de matéria específica',
    'pergunta_99_alternativa_3':'obedecem a quórum especial',
    'pergunta_99_alternativa_4':'todas as alternativas anteriores',
    'pergunta_99_resposta_correta':'todas as alternativas anteriores',
    'pergunta_99_justificativa':'As sessões extraordinárias seguem todas essas regras regimentais.',

    'pergunta_100':'Conforme o Regimento Interno, as Comissões Temporárias têm prazo de funcionamento de:',
    'pergunta_100_alternativa_1':'90 dias, prorrogável por igual período',
    'pergunta_100_alternativa_2':'120 dias, não prorrogável',
    'pergunta_100_alternativa_3':'60 dias, prorrogável uma vez',
    'pergunta_100_alternativa_4':'Até o final da legislatura',
    'pergunta_100_resposta_correta':'90 dias, prorrogável por igual período',
    'pergunta_100_justificativa':'As Comissões Temporárias são constituídas por prazo determinado de 90 dias, podendo ser prorrogadas por igual período mediante deliberação do Plenário.'
}