const perguntas = {
  // 1
  'pergunta_1':'De acordo com o Regimento Interno da Câmara de Caxias do Sul, a função legislativa consiste em:',
  'pergunta_1_alternativa_1':'Elaborar, apreciar, votar, modificar e revogar leis municipais.',
  'pergunta_1_alternativa_2':'Fiscalizar as contas do Executivo.',
  'pergunta_1_alternativa_3':'Julgar infrações político-administrativas.',
  'pergunta_1_alternativa_4':'Administrar o orçamento interno da Câmara.',
  'pergunta_1_resposta_correta':'Elaborar, apreciar, votar, modificar e revogar leis municipais.',
  'pergunta_1_justificativa':'O artigo 5º, §1º da Resolução 244/A estabelece que a função legislativa consiste na elaboração, apreciação, votação, modificação e revogação de leis de competência municipal.',

  //-----------------------------------
  // 2
  'pergunta_2':'A função de fiscalização financeira e controle externo da Câmara é exercida:',
  'pergunta_2_alternativa_1':'Sem auxílio de qualquer órgão externo.',
  'pergunta_2_alternativa_2':'Com o auxílio do Tribunal de Contas do Estado.',
  'pergunta_2_alternativa_3':'Pela Controladoria-Geral do Município.',
  'pergunta_2_alternativa_4':'Pelo Ministério Público Estadual.',
  'pergunta_2_resposta_correta':'Com o auxílio do Tribunal de Contas do Estado.',
  'pergunta_2_justificativa':'Segundo o art. 5º, §2º do Regimento, a Câmara exerce o controle financeiro e de contas com o auxílio do Tribunal de Contas do Estado.',

  //----------------------------------
  // 3
  'pergunta_3':'Assumirá a presidência da Sessão Solene de Instalação:',
  'pergunta_3_alternativa_1':'O vereador mais votado.',
  'pergunta_3_alternativa_2':'O vereador mais idoso.',
  'pergunta_3_alternativa_3':'O vereador com mais mandatos.',
  'pergunta_3_alternativa_4':'O prefeito eleito.',
  'pergunta_3_resposta_correta':'O vereador mais idoso.',
  'pergunta_3_justificativa':'O art. 6º, §1º determina que o vereador mais idoso preside a Sessão Solene de Instalação.',

  //----------------------------------
  // 4
  'pergunta_4':'A Ordem do Dia é o momento da sessão destinado a:',
  'pergunta_4_alternativa_1':'Registro de presença.',
  'pergunta_4_alternativa_2':'Leitura de expedientes.',
  'pergunta_4_alternativa_3':'Discussão e votação das matérias incluídas na pauta.',
  'pergunta_4_alternativa_4':'Comunicações pessoais dos vereadores.',
  'pergunta_4_resposta_correta':'Discussão e votação das matérias incluídas na pauta.',
  'pergunta_4_justificativa':'A Ordem do Dia é a fase da sessão em que se discutem e votam proposições previamente incluídas na pauta.',

  //----------------------------------
  // 5
  'pergunta_5':'A Mesa Diretora da Câmara é composta por:',
  'pergunta_5_alternativa_1':'Presidente, Vice-Presidente e Secretário.',
  'pergunta_5_alternativa_2':'Presidente, 1º e 2º Vice-Presidentes, 1º e 2º Secretários.',
  'pergunta_5_alternativa_3':'Presidente e dois Secretários.',
  'pergunta_5_alternativa_4':'Presidente, Vice-Presidente e Líder de Governo.',
  'pergunta_5_resposta_correta':'Presidente, 1º e 2º Vice-Presidentes, 1º e 2º Secretários.',
  'pergunta_5_justificativa':'Conforme o art. 13, a Mesa é composta por um Presidente, dois Vice-Presidentes e dois Secretários.',

  //----------------------------------
  // 6
  'pergunta_6':'As funções dos membros da Mesa cessarão:',
  'pergunta_6_alternativa_1':'Somente ao final do mandato.',
  'pergunta_6_alternativa_2':'Ao final do ano legislativo, por renúncia, perda do mandato ou destituição.',
  'pergunta_6_alternativa_3':'Apenas com a morte do titular.',
  'pergunta_6_alternativa_4':'Com aprovação de dois terços do plenário.',
  'pergunta_6_resposta_correta':'Ao final do ano legislativo, por renúncia, perda do mandato ou destituição.',
  'pergunta_6_justificativa':'Segundo o art. 23, o término ocorre nessas hipóteses.',

  //----------------------------------
  // 7
  'pergunta_7':'As Sessões Ordinárias e Extraordinárias só podem ser abertas com:',
  'pergunta_7_alternativa_1':'Um terço dos vereadores presentes.',
  'pergunta_7_alternativa_2':'Metade mais um dos vereadores.',
  'pergunta_7_alternativa_3':'Um quarto dos vereadores.',
  'pergunta_7_alternativa_4':'Dois terços dos vereadores.',
  'pergunta_7_resposta_correta':'Um terço dos vereadores.',
  'pergunta_7_justificativa':'Conforme o art. 130, a presença mínima para abertura é de um terço dos membros.',

  //----------------------------------
  // 8
  'pergunta_8':'A duração máxima das sessões ordinárias e extraordinárias é de:',
  'pergunta_8_alternativa_1':'Uma hora.',
  'pergunta_8_alternativa_2':'Duas horas.',
  'pergunta_8_alternativa_3':'Três horas.',
  'pergunta_8_alternativa_4':'Quatro horas.',
  'pergunta_8_resposta_correta':'Três horas.',
  'pergunta_8_justificativa':'O art. 130 também fixa o limite máximo de duração das sessões em três horas.',

  //----------------------------------
  // 9
  'pergunta_9':'As Sessões Solenes:',
  'pergunta_9_alternativa_1':'Dependem de quorum mínimo.',
  'pergunta_9_alternativa_2':'Podem deliberar matérias urgentes.',
  'pergunta_9_alternativa_3':'Independem de quorum por terem caráter apenas cerimonial.',
  'pergunta_9_alternativa_4':'São realizadas apenas mediante convocação do Prefeito.',
  'pergunta_9_resposta_correta':'Independem de quorum por terem caráter apenas cerimonial.',
  'pergunta_9_justificativa':'As sessões solenes têm caráter comemorativo e não deliberativo, portanto independem de quorum.',

  //----------------------------------
  // 10
  'pergunta_10':'As contas do Prefeito e da Mesa da Câmara devem ser prestadas:',
  'pergunta_10_alternativa_1':'Até noventa dias após o encerramento do exercício.',
  'pergunta_10_alternativa_2':'Em até sessenta dias após o parecer do Tribunal de Contas.',
  'pergunta_10_alternativa_3':'Diretamente ao Legislativo sem prazo fixo.',
  'pergunta_10_alternativa_4':'Até o fim da legislatura.',
  'pergunta_10_resposta_correta':'Em até sessenta dias após o parecer do Tribunal de Contas.',
  'pergunta_10_justificativa':'O Regimento prevê prazo de 60 dias para a Câmara deliberar após o recebimento do parecer prévio do Tribunal de Contas.',

  //----------------------------------
  // 11
  'pergunta_11':'O Presidente da Câmara só vota:',
  'pergunta_11_alternativa_1':'Sempre.',
  'pergunta_11_alternativa_2':'Quando houver empate, votação secreta ou matéria que exija 2/3 dos votos.',
  'pergunta_11_alternativa_3':'Em casos de urgência.',
  'pergunta_11_alternativa_4':'Quando autorizado pelo plenário.',
  'pergunta_11_resposta_correta':'Quando houver empate, votação secreta ou matéria que exija 2/3 dos votos.',
  'pergunta_11_justificativa':'O art. 29 do Regimento determina essas hipóteses específicas para o voto do Presidente.',

  //----------------------------------
  // 12
  'pergunta_12':'As Comissões Permanentes são órgãos:',
  'pergunta_12_alternativa_1':'De assessoramento técnico e político, com atuação contínua.',
  'pergunta_12_alternativa_2':'De caráter apenas temporário.',
  'pergunta_12_alternativa_3':'Formados por servidores efetivos.',
  'pergunta_12_alternativa_4':'Sem poder de parecer.',
  'pergunta_12_resposta_correta':'De assessoramento técnico e político, com atuação contínua.',
  'pergunta_12_justificativa':'O Regimento define as comissões permanentes como órgãos técnicos e políticos de caráter permanente.',

  //----------------------------------
  // 13
  'pergunta_13':'A Câmara Municipal reunir-se-á anualmente, em sessão legislativa ordinária:',
  'pergunta_13_alternativa_1':'De 1º de janeiro a 22 de dezembro.',
  'pergunta_13_alternativa_2':'De 15 de janeiro a 22 de dezembro.',
  'pergunta_13_alternativa_3':'De 1º de fevereiro a 15 de dezembro.',
  'pergunta_13_alternativa_4':'De 2 de fevereiro a 15 de dezembro.',
  'pergunta_13_resposta_correta':'De 1º de fevereiro a 15 de dezembro.',
  'pergunta_13_justificativa':'O art. 125 estabelece o período da sessão legislativa ordinária.',

  //----------------------------------
  // 14
  'pergunta_14':'As funções da Câmara incluem, entre outras:',
  'pergunta_14_alternativa_1':'Executiva e judiciária.',
  'pergunta_14_alternativa_2':'Legislativa, fiscalizadora, de julgamento e assessoramento.',
  'pergunta_14_alternativa_3':'Administrativa e privada.',
  'pergunta_14_alternativa_4':'Judicial e arbitral.',
  'pergunta_14_resposta_correta':'Legislativa, fiscalizadora, de julgamento e assessoramento.',
  'pergunta_14_justificativa':'Essas são as funções descritas no art. 5º do Regimento.',

  //----------------------------------
  // 15
  'pergunta_15':'Durante a Sessão Solene de Instalação, a posse do Prefeito ocorre:',
  'pergunta_15_alternativa_1':'Antes do compromisso legal.',
  'pergunta_15_alternativa_2':'Após a prestação do compromisso e entrega de declaração de bens.',
  'pergunta_15_alternativa_3':'Após a eleição da Mesa Diretora.',
  'pergunta_15_alternativa_4':'Somente após aprovação do Tribunal de Contas.',
  'pergunta_15_resposta_correta':'Após a prestação do compromisso e entrega de declaração de bens.',
  'pergunta_15_justificativa':'O art. 6º, §2º define essa sequência da Sessão Solene de Instalação.',

  //----------------------------------
  // 16
  'pergunta_16':'A Comissão de Constituição, Justiça e Legislação tem como competência específica:',
  'pergunta_16_alternativa_1':'Opinar sobre proposições e emendas em tramitação.',
  'pergunta_16_alternativa_2':'Fiscalizar obras públicas.',
  'pergunta_16_alternativa_3':'Acompanhar o orçamento anual.',
  'pergunta_16_alternativa_4':'Promover debates sobre meio ambiente.',
  'pergunta_16_resposta_correta':'Opinar sobre proposições e emendas em tramitação.',
  'pergunta_16_justificativa':'Compete à Comissão de Constituição e Justiça emitir parecer sobre a legalidade e constitucionalidade de proposições.',

  //----------------------------------
  // 17
  'pergunta_17':'As Comissões Temporárias têm como característica:',
  'pergunta_17_alternativa_1':'Existirem por prazo determinado para tratar de assuntos específicos.',
  'pergunta_17_alternativa_2':'Terem duração igual à legislatura.',
  'pergunta_17_alternativa_3':'Substituírem as Comissões Permanentes.',
  'pergunta_17_alternativa_4':'Serem compostas por servidores efetivos.',
  'pergunta_17_resposta_correta':'Existirem por prazo determinado para tratar de assuntos específicos.',
  'pergunta_17_justificativa':'O Regimento diferencia as Comissões Temporárias pelas suas finalidades transitórias e prazo definido.',

  //----------------------------------
  // 18
  'pergunta_18':'As Sessões Extraordinárias são realizadas:',
  'pergunta_18_alternativa_1':'Para tratar de matérias urgentes, mediante convocação.',
  'pergunta_18_alternativa_2':'Somente para homenagens.',
  'pergunta_18_alternativa_3':'Sem necessidade de convocação.',
  'pergunta_18_alternativa_4':'Apenas durante o recesso.',
  'pergunta_18_resposta_correta':'Para tratar de matérias urgentes, mediante convocação.',
  'pergunta_18_justificativa':'As sessões extraordinárias são convocadas para matérias urgentes e relevantes.',

  //----------------------------------
  // 19
  'pergunta_19':'As sessões extraordinárias e solenes independem de quorum para:',
  'pergunta_19_alternativa_1':'Convocação e deliberação, respectivamente.',
  'pergunta_19_alternativa_2':'Ambas as etapas.',
  'pergunta_19_alternativa_3':'Apenas para encerramento.',
  'pergunta_19_alternativa_4':'Nenhuma etapa.',
  'pergunta_19_resposta_correta':'Convocação e deliberação, respectivamente.',
  'pergunta_19_justificativa':'Extraordinária não depende de quorum para convocação, e a solene independe totalmente por não deliberar.',
  
  //----------------------------------
  // 20
  'pergunta_20':'Proposição é:',
  'pergunta_20_alternativa_1':'Qualquer matéria sujeita à deliberação da Câmara.',
  'pergunta_20_alternativa_2':'Apenas projeto de lei.',
  'pergunta_20_alternativa_3':'Moção de aplauso.',
  'pergunta_20_alternativa_4':'Expediente administrativo.',
  'pergunta_20_resposta_correta':'Qualquer matéria sujeita à deliberação da Câmara.',
  'pergunta_20_justificativa':'O Regimento define proposição como toda matéria sobre a qual deva pronunciar-se a Câmara.',

  //----------------------------------
//----------------------------------
  'pergunta_21':'As Comissões Temporárias podem ser criadas para:',
  'pergunta_21_alternativa_1':'Tratar de assuntos de caráter permanente.',
  'pergunta_21_alternativa_2':'Tratar de assuntos específicos e por prazo determinado.',
  'pergunta_21_alternativa_3':'Substituir a Mesa Diretora.',
  'pergunta_21_alternativa_4':'Fiscalizar obras públicas.',
  'pergunta_21_resposta_correta':'Tratar de assuntos específicos e por prazo determinado.',
  'pergunta_21_justificativa':'O Regimento define que as Comissões Temporárias são criadas para assuntos específicos e têm duração limitada.',

  //----------------------------------
  'pergunta_22':'A criação de Comissões Parlamentares de Inquérito depende de requerimento de:',
  'pergunta_22_alternativa_1':'Um terço dos vereadores.',
  'pergunta_22_alternativa_2':'Maioria simples do plenário.',
  'pergunta_22_alternativa_3':'Dois terços dos vereadores.',
  'pergunta_22_alternativa_4':'Apenas do Presidente da Câmara.',
  'pergunta_22_resposta_correta':'Um terço dos vereadores.',
  'pergunta_22_justificativa':'Conforme o art. 168 do Regimento, a CPI é criada mediante requerimento de um terço dos vereadores.',

  //----------------------------------
  'pergunta_23':'As proposições podem ser retiradas:',
  'pergunta_23_alternativa_1':'A qualquer tempo pelo autor, antes da votação.',
  'pergunta_23_alternativa_2':'Somente pela Mesa Diretora.',
  'pergunta_23_alternativa_3':'Somente antes da leitura em plenário.',
  'pergunta_23_alternativa_4':'Após a aprovação final.',
  'pergunta_23_resposta_correta':'A qualquer tempo pelo autor, antes da votação.',
  'pergunta_23_justificativa':'O autor pode retirar sua proposição até o início da votação, conforme as regras regimentais.',

  //----------------------------------
  'pergunta_24':'O veto do Prefeito deverá ser apreciado pela Câmara no prazo de:',
  'pergunta_24_alternativa_1':'10 dias úteis.',
  'pergunta_24_alternativa_2':'30 dias corridos.',
  'pergunta_24_alternativa_3':'45 dias úteis.',
  'pergunta_24_alternativa_4':'60 dias corridos.',
  'pergunta_24_resposta_correta':'30 dias corridos.',
  'pergunta_24_justificativa':'O Regimento fixa o prazo de 30 dias para apreciação do veto pelo Legislativo.',

  //----------------------------------
  'pergunta_25':'A promulgação de lei é ato que:',
  'pergunta_25_alternativa_1':'Compete sempre ao Prefeito.',
  'pergunta_25_alternativa_2':'Compete ao Presidente da Câmara quando o Prefeito não o faz.',
  'pergunta_25_alternativa_3':'Depende de aprovação judicial.',
  'pergunta_25_alternativa_4':'É feito apenas pelo Governador do Estado.',
  'pergunta_25_resposta_correta':'Compete ao Presidente da Câmara quando o Prefeito não o faz.',
  'pergunta_25_justificativa':'Se o Prefeito não promulgar a lei no prazo legal, o Presidente da Câmara o fará, conforme o Regimento.',

  //----------------------------------
  'pergunta_26':'A sanção tácita ocorre quando:',
  'pergunta_26_alternativa_1':'O Prefeito devolve o projeto com veto parcial.',
  'pergunta_26_alternativa_2':'O Prefeito não se manifesta no prazo de 15 dias úteis.',
  'pergunta_26_alternativa_3':'O projeto é aprovado por unanimidade.',
  'pergunta_26_alternativa_4':'O Prefeito promulga a lei antes do prazo.',
  'pergunta_26_resposta_correta':'O Prefeito não se manifesta no prazo de 15 dias úteis.',
  'pergunta_26_justificativa':'A ausência de manifestação do Prefeito no prazo de 15 dias úteis implica sanção tácita.',

  //----------------------------------
  'pergunta_27':'A iniciativa de lei sobre matéria orçamentária é de competência:',
  'pergunta_27_alternativa_1':'Exclusiva do Prefeito.',
  'pergunta_27_alternativa_2':'Compartilhada entre Prefeito e Câmara.',
  'pergunta_27_alternativa_3':'Exclusiva da Mesa Diretora.',
  'pergunta_27_alternativa_4':'Do Tribunal de Contas.',
  'pergunta_27_resposta_correta':'Exclusiva do Prefeito.',
  'pergunta_27_justificativa':'A competência para propor leis orçamentárias é privativa do Executivo Municipal.',

  //----------------------------------
  'pergunta_28':'As emendas apresentadas aos projetos de lei orçamentária devem ser:',
  'pergunta_28_alternativa_1':'Aprovadas por unanimidade.',
  'pergunta_28_alternativa_2':'Compatíveis com o plano plurianual e com a lei de diretrizes orçamentárias.',
  'pergunta_28_alternativa_3':'Apenas de iniciativa popular.',
  'pergunta_28_alternativa_4':'Feitas exclusivamente pelo Executivo.',
  'pergunta_28_resposta_correta':'Compatíveis com o plano plurianual e com a lei de diretrizes orçamentárias.',
  'pergunta_28_justificativa':'O Regimento impõe que as emendas respeitem o PPA e a LDO.',

  //----------------------------------
  'pergunta_29':'A Câmara Municipal julga o Prefeito e o Vice-Prefeito quando:',
  'pergunta_29_alternativa_1':'Cometem infrações penais.',
  'pergunta_29_alternativa_2':'Incorrem em infrações político-administrativas.',
  'pergunta_29_alternativa_3':'Descumprem decisões judiciais.',
  'pergunta_29_alternativa_4':'Não executam obras públicas.',
  'pergunta_29_resposta_correta':'Incorrem em infrações político-administrativas.',
  'pergunta_29_justificativa':'Essa é uma das funções da Câmara, conforme o art. 5º.',

  //----------------------------------
  'pergunta_30':'A licença para tratar de interesse particular do vereador deve ter duração mínima de:',
  'pergunta_30_alternativa_1':'10 dias.',
  'pergunta_30_alternativa_2':'20 dias.',
  'pergunta_30_alternativa_3':'30 dias.',
  'pergunta_30_alternativa_4':'60 dias.',
  'pergunta_30_resposta_correta':'30 dias.',
  'pergunta_30_justificativa':'O vereador pode licenciar-se por motivo particular por período nunca inferior a 30 dias.',

  //----------------------------------
  'pergunta_31':'O vereador pode licenciar-se por motivo de doença:',
  'pergunta_31_alternativa_1':'Sem necessidade de comprovação.',
  'pergunta_31_alternativa_2':'Mediante atestado médico comprovado.',
  'pergunta_31_alternativa_3':'Apenas com aprovação do Prefeito.',
  'pergunta_31_alternativa_4':'Com aval do Tribunal de Contas.',
  'pergunta_31_resposta_correta':'Mediante atestado médico comprovado.',
  'pergunta_31_justificativa':'A licença por moléstia deve ser comprovada por documento médico.',

  //----------------------------------
  'pergunta_32':'O vereador que assumir cargo público na administração direta ou indireta:',
  'pergunta_32_alternativa_1':'Perde automaticamente o mandato.',
  'pergunta_32_alternativa_2':'Fica licenciado enquanto durar o exercício do cargo.',
  'pergunta_32_alternativa_3':'Permanece acumulando funções.',
  'pergunta_32_alternativa_4':'Deve renunciar imediatamente.',
  'pergunta_32_resposta_correta':'Fica licenciado enquanto durar o exercício do cargo.',
  'pergunta_32_justificativa':'O vereador deve comunicar a Mesa e fica licenciado enquanto exercer função na administração pública.',

  //----------------------------------
  'pergunta_33':'A eleição da Mesa Diretora ocorre:',
  'pergunta_33_alternativa_1':'Na última sessão do ano legislativo.',
  'pergunta_33_alternativa_2':'Na primeira sessão do primeiro ano da legislatura.',
  'pergunta_33_alternativa_3':'Por votação secreta em qualquer sessão.',
  'pergunta_33_alternativa_4':'Apenas após aprovação do Prefeito.',
  'pergunta_33_resposta_correta':'Na primeira sessão do primeiro ano da legislatura.',
  'pergunta_33_justificativa':'A eleição e posse da Mesa ocorrem na primeira sessão de instalação da legislatura.',

  //----------------------------------
  'pergunta_34':'O Presidente da Câmara exerce, entre outras, a função de:',
  'pergunta_34_alternativa_1':'Julgar infrações disciplinares.',
  'pergunta_34_alternativa_2':'Representar a Câmara em juízo e fora dele.',
  'pergunta_34_alternativa_3':'Fiscalizar o Prefeito.',
  'pergunta_34_alternativa_4':'Substituir o Vice-Presidente.',
  'pergunta_34_resposta_correta':'Representar a Câmara em juízo e fora dele.',
  'pergunta_34_justificativa':'O art. 27 define como função do Presidente representar a Câmara em todas as instâncias.',

  //----------------------------------
  'pergunta_35':'Durante o recesso parlamentar, o funcionamento da Câmara é assegurado por:',
  'pergunta_35_alternativa_1':'Comissão Representativa.',
  'pergunta_35_alternativa_2':'Comissão de Ética.',
  'pergunta_35_alternativa_3':'Comissão Especial.',
  'pergunta_35_alternativa_4':'Comissão de Justiça.',
  'pergunta_35_resposta_correta':'Comissão Representativa.',
  'pergunta_35_justificativa':'A Comissão Representativa exerce as atribuições do Legislativo durante o recesso parlamentar.',

  //----------------------------------
  'pergunta_36':'Os prazos regimentais contam-se:',
  'pergunta_36_alternativa_1':'Em dias corridos.',
  'pergunta_36_alternativa_2':'Apenas em dias úteis.',
  'pergunta_36_alternativa_3':'Somente durante o recesso.',
  'pergunta_36_alternativa_4':'Excluindo sábados, domingos e feriados.',
  'pergunta_36_resposta_correta':'Em dias corridos.',
  'pergunta_36_justificativa':'Salvo disposição em contrário, os prazos contam-se em dias corridos.',

  //----------------------------------
  'pergunta_37':'As sessões poderão ser prorrogadas:',
  'pergunta_37_alternativa_1':'Pelo Presidente, a pedido de vereador, por até 30 minutos.',
  'pergunta_37_alternativa_2':'Pelo Prefeito.',
  'pergunta_37_alternativa_3':'Somente pelo plenário por unanimidade.',
  'pergunta_37_alternativa_4':'Por iniciativa do Secretário.',
  'pergunta_37_resposta_correta':'Pelo Presidente, a pedido de vereador, por até 30 minutos.',
  'pergunta_37_justificativa':'O Presidente pode prorrogar a sessão mediante solicitação e aprovação do plenário.',

  //----------------------------------
  'pergunta_38':'A votação simbólica é caracterizada por:',
  'pergunta_38_alternativa_1':'Manifestação verbal nominal.',
  'pergunta_38_alternativa_2':'Levantada de mãos ou permanência como se encontra.',
  'pergunta_38_alternativa_3':'Escrutínio secreto.',
  'pergunta_38_alternativa_4':'Utilização de urna.',
  'pergunta_38_resposta_correta':'Levantada de mãos ou permanência como se encontra.',
  'pergunta_38_justificativa':'Na votação simbólica, os vereadores manifestam-se por gestos ou permanência.',

  //----------------------------------
  'pergunta_39':'A votação nominal ocorre quando:',
  'pergunta_39_alternativa_1':'Cada vereador declara seu voto publicamente.',
  'pergunta_39_alternativa_2':'Há unanimidade no plenário.',
  'pergunta_39_alternativa_3':'O Presidente decide sozinho.',
  'pergunta_39_alternativa_4':'A matéria é de iniciativa popular.',
  'pergunta_39_resposta_correta':'Cada vereador declara seu voto publicamente.',
  'pergunta_39_justificativa':'A votação nominal é feita com chamada nominal dos vereadores e registro de voto individual.',

  //----------------------------------
  'pergunta_40':'As atas das sessões devem ser aprovadas:',
  'pergunta_40_alternativa_1':'Na mesma sessão em que foram redigidas.',
  'pergunta_40_alternativa_2':'Na sessão seguinte.',
  'pergunta_40_alternativa_3':'Somente ao final do mês.',
  'pergunta_40_alternativa_4':'Pelo Presidente.',
  'pergunta_40_resposta_correta':'Na sessão seguinte.',
  'pergunta_40_justificativa':'O Regimento prevê que as atas sejam lidas e aprovadas na sessão subsequente.',

  //----------------------------------
  'pergunta_41':'As sessões plenárias da Câmara são públicas, exceto:',
  'pergunta_41_alternativa_1':'Quando houver deliberação para que sejam secretas.',
  'pergunta_41_alternativa_2':'Durante votações simbólicas.',
  'pergunta_41_alternativa_3':'Quando tratar de moções.',
  'pergunta_41_alternativa_4':'Durante posse do Prefeito.',
  'pergunta_41_resposta_correta':'Quando houver deliberação para que sejam secretas.',
  'pergunta_41_justificativa':'Somente por deliberação da maioria absoluta é possível sessão secreta.',

  //----------------------------------
  'pergunta_42':'A tribuna livre é destinada:',
  'pergunta_42_alternativa_1':'Aos vereadores.',
  'pergunta_42_alternativa_2':'À participação de entidades e cidadãos previamente inscritos.',
  'pergunta_42_alternativa_3':'Aos servidores da Câmara.',
  'pergunta_42_alternativa_4':'Exclusivamente ao Prefeito.',
  'pergunta_42_resposta_correta':'À participação de entidades e cidadãos previamente inscritos.',
  'pergunta_42_justificativa':'A Tribuna Livre é espaço quinzenal destinado a entidades e cidadãos conforme regulamento.',

  //----------------------------------
  'pergunta_43':'Compete à Comissão de Ética Parlamentar:',
  'pergunta_43_alternativa_1':'Emitir pareceres sobre proposições de lei.',
  'pergunta_43_alternativa_2':'Apurar fatos relativos à conduta ética dos vereadores.',
  'pergunta_43_alternativa_3':'Julgar contas do Executivo.',
  'pergunta_43_alternativa_4':'Fiscalizar licitações.',
  'pergunta_43_resposta_correta':'Apurar fatos relativos à conduta ética dos vereadores.',
  'pergunta_43_justificativa':'A Comissão de Ética zela pelo decoro e apura faltas éticas de vereadores.',

  //----------------------------------
  'pergunta_44':'A destituição de membro da Mesa requer:',
  'pergunta_44_alternativa_1':'Maioria simples dos presentes.',
  'pergunta_44_alternativa_2':'Voto favorável de dois terços dos vereadores.',
  'pergunta_44_alternativa_3':'Aprovação unânime.',
  'pergunta_44_alternativa_4':'Decisão do Prefeito.',
  'pergunta_44_resposta_correta':'Voto favorável de dois terços dos vereadores.',
  'pergunta_44_justificativa':'O art. 24 exige dois terços para destituição de membro da Mesa.',

  //----------------------------------
  'pergunta_45':'As matérias de iniciativa exclusiva do Prefeito não podem:',
  'pergunta_45_alternativa_1':'Receber emendas que aumentem despesa.',
  'pergunta_45_alternativa_2':'Ser discutidas em plenário.',
  'pergunta_45_alternativa_3':'Ser arquivadas.',
  'pergunta_45_alternativa_4':'Receber parecer de comissão.',
  'pergunta_45_resposta_correta':'Receber emendas que aumentem despesa.',
  'pergunta_45_justificativa':'É vedada a apresentação de emendas que aumentem despesa em proposições de iniciativa exclusiva do Executivo.',

  //----------------------------------
  'pergunta_46':'O projeto de decreto legislativo destina-se a:',
  'pergunta_46_alternativa_1':'Regular matérias de competência exclusiva da Câmara.',
  'pergunta_46_alternativa_2':'Ser sancionado pelo Prefeito.',
  'pergunta_46_alternativa_3':'Alterar a Lei Orgânica.',
  'pergunta_46_alternativa_4':'Criar cargos públicos.',
  'pergunta_46_resposta_correta':'Regular matérias de competência exclusiva da Câmara.',
  'pergunta_46_justificativa':'Projetos de decreto legislativo tratam de matérias internas ou exclusivas do Legislativo.',

  //----------------------------------
  'pergunta_47':'As moções são proposições que visam:',
  'pergunta_47_alternativa_1':'Apenas alterar leis.',
  'pergunta_47_alternativa_2':'Expressar posicionamento da Câmara sobre determinado assunto.',
  'pergunta_47_alternativa_3':'Criar novas comissões.',
  'pergunta_47_alternativa_4':'Regulamentar o regimento interno.',
  'pergunta_47_resposta_correta':'Expressar posicionamento da Câmara sobre determinado assunto.',
  'pergunta_47_justificativa':'As moções servem para manifestar apoio, repúdio ou pesar, entre outros',


  //----------------------------------
  'pergunta_48':'Durante a discussão de uma proposição, o vereador pode usar a palavra:',
  'pergunta_48_alternativa_1':'Por tempo ilimitado.',
  'pergunta_48_alternativa_2':'Por até 10 minutos, prorrogáveis uma vez pelo Presidente.',
  'pergunta_48_alternativa_3':'Somente mediante requerimento escrito.',
  'pergunta_48_alternativa_4':'Apenas com autorização do Prefeito.',
  'pergunta_48_resposta_correta':'Por até 10 minutos, prorrogáveis uma vez pelo Presidente.',
  'pergunta_48_justificativa':'O Regimento estabelece limite de 10 minutos por vereador na discussão de cada proposição.',

  //----------------------------------
  'pergunta_49':'O prazo para o contribuinte examinar as contas apresentadas pelo Prefeito é de:',
  'pergunta_49_alternativa_1':'30 dias.',
  'pergunta_49_alternativa_2':'45 dias.',
  'pergunta_49_alternativa_3':'60 dias.',
  'pergunta_49_alternativa_4':'90 dias.',
  'pergunta_49_resposta_correta':'60 dias.',
  'pergunta_49_justificativa':'Após publicação de edital, o contribuinte tem 60 dias para examinar e apresentar questionamentos às contas.',

  //----------------------------------
  'pergunta_50':'Compete à Câmara Municipal, conforme o Regimento Interno:',
  'pergunta_50_alternativa_1':'Julgar as contas do Prefeito e da Mesa da Câmara.',
  'pergunta_50_alternativa_2':'Executar diretamente as leis municipais.',
  'pergunta_50_alternativa_3':'Representar o Município em juízo.',
  'pergunta_50_alternativa_4':'Fiscalizar apenas obras públicas.',
  'pergunta_50_resposta_correta':'Julgar as contas do Prefeito e da Mesa da Câmara.',
  'pergunta_50_justificativa':'O art. 216 e seguintes dispõem que cabe à Câmara deliberar sobre as contas do Prefeito e da própria Mesa.',



  'pergunta_51':'O Poder Legislativo do Município é exercido por qual órgão?',
  'pergunta_51_alternativa_1':'Assembleia Municipal',
  'pergunta_51_alternativa_2':'Câmara Municipal de Vereadores',
  'pergunta_51_alternativa_3':'Conselho Municipal',
  'pergunta_51_alternativa_4':'Mesa Executiva',
  'pergunta_51_resposta_correta':'Câmara Municipal de Vereadores',
  'pergunta_51_justificativa':'Art. 40: O Poder Legislativo é exercido pela Câmara Municipal de Vereadores.',

  'pergunta_52':'Qual é o número de vereadores fixado para a legislatura referida na Lei Orgânica?',
  'pergunta_52_alternativa_1':'15 vereadores',
  'pergunta_52_alternativa_2':'21 vereadores',
  'pergunta_52_alternativa_3':'25 vereadores',
  'pergunta_52_alternativa_4':'19 vereadores',
  'pergunta_52_resposta_correta':'21 vereadores',
  'pergunta_52_justificativa':'Parágrafo do Art. 40 fixa-se em 21 (vinte e um) Vereadores a composição numérica da Câmara.',

  'pergunta_53':'Em que período anual a Câmara Municipal reunir-se-á, segundo a Lei Orgânica?',
  'pergunta_53_alternativa_1':'1º de janeiro a 31 de dezembro',
  'pergunta_53_alternativa_2':'1º de março a 30 de novembro',
  'pergunta_53_alternativa_3':'1º de fevereiro a 15 de dezembro',
  'pergunta_53_alternativa_4':'1º de abril a 30 de outubro',
  'pergunta_53_resposta_correta':'1º de fevereiro a 15 de dezembro',
  'pergunta_53_justificativa':'Art. 41: A Câmara reunir-se-á anualmente de 1º de fevereiro a 15 de dezembro.',

  'pergunta_54':'Quando realiza-se a primeira sessão de cada legislatura para posse e eleição da Mesa?',
  'pergunta_54_alternativa_1':'1º de fevereiro',
  'pergunta_54_alternativa_2':'1º de janeiro',
  'pergunta_54_alternativa_3':'15 de dezembro',
  'pergunta_54_alternativa_4':'31 de dezembro',
  'pergunta_54_resposta_correta':'1º de janeiro',
  'pergunta_54_justificativa':'Art. 42: A primeira sessão de cada legislatura realizar-se-á no dia 1º de janeiro para posse e eleição da Mesa.',

  'pergunta_55':'Qual é o mandato dos membros da Mesa da Câmara conforme a Lei Orgânica?',
  'pergunta_55_alternativa_1':'6 meses',
  'pergunta_55_alternativa_2':'2 anos',
  'pergunta_55_alternativa_3':'1 ano',
  'pergunta_55_alternativa_4':'4 anos',
  'pergunta_55_resposta_correta':'1 ano',
  'pergunta_55_justificativa':'Parágrafo do Art. 42: É de um ano o mandato dos membros da Mesa, com possibilidade de recondução por igual período.',

  'pergunta_56':'Prazo para o vereador que não tomou posse na sessão de 1º de janeiro regularizar sua posse?',
  'pergunta_56_alternativa_1':'7 dias',
  'pergunta_56_alternativa_2':'15 dias',
  'pergunta_56_alternativa_3':'30 dias',
  'pergunta_56_alternativa_4':'45 dias',
  'pergunta_56_resposta_correta':'15 dias',
  'pergunta_56_justificativa':'Art. 43: O Vereador que não tomar posse deverá fazê-lo dentro de quinze dias do início do funcionamento da Câmara, sob pena de perda do mandato.',

  'pergunta_57':'O que os Vereadores devem fazer no ato da posse e ao término do mandato?',
  'pergunta_57_alternativa_1':'Entrega de relatório de atividades',
  'pergunta_57_alternativa_2':'Declaração de bens',
  'pergunta_57_alternativa_3':'Assinatura de termo de compromisso de sigilo',
  'pergunta_57_alternativa_4':'Exibição de certidão eleitoral',
  'pergunta_57_resposta_correta':'Declaração de bens',
  'pergunta_57_justificativa':'Art. 44: No ato da posse e ao término do mandato, os Vereadores deverão fazer a declaração de seus bens.',

  'pergunta_58':'Quem pode convocar extraordinariamente a Câmara Municipal?',
  'pergunta_58_alternativa_1':'Prefeito, Presidente da Câmara e maioria dos Vereadores',
  'pergunta_58_alternativa_2':'Apenas o Prefeito',
  'pergunta_58_alternativa_3':'Apenas a Mesa',
  'pergunta_58_alternativa_4':'O Tribunal de Contas',
  'pergunta_58_resposta_correta':'Prefeito, Presidente da Câmara e maioria dos Vereadores',
  'pergunta_58_justificativa':'Art. 45: A convocação extraordinária caberá ao Prefeito, ao Presidente da Câmara e à maioria de seus membros.',

  'pergunta_59':'Como será comunicada a convocação extraordinária aos Vereadores?',
  'pergunta_59_alternativa_1':'Por edital no jornal',
  'pergunta_59_alternativa_2':'Por transmissão pública',
  'pergunta_59_alternativa_3':'Por convocação pessoal e escrita',
  'pergunta_59_alternativa_4':'Por email institucional',
  'pergunta_59_resposta_correta':'Por convocação pessoal e escrita',
  'pergunta_59_justificativa':'Art. 45, §1º: A convocação extraordinária será levada ao conhecimento dos Vereadores através de convocação pessoal e escrita.',

  'pergunta_60':'Onde as sessões da Câmara deverão ser realizadas, sob pena de nulidade?',
  'pergunta_60_alternativa_1':'Em qualquer local público',
  'pergunta_60_alternativa_2':'Em recinto destinado ao seu funcionamento',
  'pergunta_60_alternativa_3':'Em salão cedido pela Prefeitura',
  'pergunta_60_alternativa_4':'Em auditório municipal',
  'pergunta_60_resposta_correta':'Em recinto destinado ao seu funcionamento',
  'pergunta_60_justificativa':'Art. 46: As sessões serão realizadas em recinto destinado ao seu funcionamento; as realizadas em outro local serão consideradas nulas, salvo motivo de força maior.',

  'pergunta_61':'As sessões da Câmara são públicas, salvo deliberação em contrário por qual maioria?',
  'pergunta_61_alternativa_1':'Maioria simples',
  'pergunta_61_alternativa_2':'Maioria absoluta',
  'pergunta_61_alternativa_3':'Dois terços dos membros',
  'pergunta_61_alternativa_4':'Unanimidade',
  'pergunta_61_resposta_correta':'Dois terços dos membros',
  'pergunta_61_justificativa':'Art. 47: As sessões serão públicas, salvo deliberação em contrário tomada por dois terços, no mínimo, de seus membros.',



  'pergunta_62':'Sobre a posse em cargo público, é correto afirmar que:',
  'pergunta_62_alternativa_1':'A posse poderá ocorrer até 30 dias após a nomeação.',
  'pergunta_62_alternativa_2':'A posse é dispensável quando o servidor já é efetivo no cargo anterior.',
  'pergunta_62_alternativa_3':'A posse deve ocorrer no prazo máximo de 10 dias a contar da nomeação.',
  'pergunta_62_alternativa_4':'A posse é ato administrativo interno e não depende de termo assinado.',
  'pergunta_62_resposta_correta':'A posse deve ocorrer no prazo máximo de 10 dias a contar da nomeação.',
  'pergunta_62_justificativa':'Conforme o regime jurídico municipal, a posse deve ocorrer no prazo de 10 dias contados da nomeação, sob pena de tornar sem efeito o ato.',
  
  'pergunta_63':'O estágio probatório tem como finalidade:',
  'pergunta_63_alternativa_1':'Avaliar apenas a capacidade técnica do servidor.',
  'pergunta_63_alternativa_2':'Verificar a aptidão e a capacidade do servidor para o cargo, como condição à estabilidade.',
  'pergunta_63_alternativa_3':'Garantir progressão funcional automática.',
  'pergunta_63_alternativa_4':'Assegurar direito a férias proporcionais.',
  'pergunta_63_resposta_correta':'Verificar a aptidão e a capacidade do servidor para o cargo, como condição à estabilidade.',
  'pergunta_63_justificativa':'O estágio probatório é o período destinado à avaliação da capacidade e do desempenho do servidor antes da aquisição da estabilidade.',
  
  'pergunta_64':'Durante o estágio probatório, o servidor poderá:',
  'pergunta_64_alternativa_1':'Solicitar licença para tratar de assuntos particulares.',
  'pergunta_64_alternativa_2':'Afastar-se para exercer mandato eletivo.',
  'pergunta_64_alternativa_3':'Ser exonerado apenas por vontade própria.',
  'pergunta_64_alternativa_4':'Afastar-se para estudar no exterior sem autorização.',
  'pergunta_64_resposta_correta':'Afastar-se para exercer mandato eletivo.',
  'pergunta_64_justificativa':'Durante o estágio probatório, o servidor pode afastar-se em hipóteses legais, como o exercício de mandato eletivo.',
  
  'pergunta_65':'A estabilidade é adquirida pelo servidor público após:',
  'pergunta_65_alternativa_1':'Um ano de efetivo exercício.',
  'pergunta_65_alternativa_2':'Dois anos de efetivo exercício.',
  'pergunta_65_alternativa_3':'Três anos de efetivo exercício e aprovação em avaliação especial de desempenho.',
  'pergunta_65_alternativa_4':'Quatro anos de exercício e aprovação em estágio probatório.',
  'pergunta_65_resposta_correta':'Três anos de efetivo exercício e aprovação em avaliação especial de desempenho.',
  'pergunta_65_justificativa':'A estabilidade é garantida após três anos de efetivo exercício e avaliação de desempenho favorável.',
  
  'pergunta_66':'O servidor estável só perderá o cargo em caso de:',
  'pergunta_66_alternativa_1':'Decisão judicial transitada em julgado ou processo administrativo disciplinar.',
  'pergunta_66_alternativa_2':'Reprovação em curso de capacitação.',
  'pergunta_66_alternativa_3':'Decisão do superior hierárquico.',
  'pergunta_66_alternativa_4':'Interesse público comprovado por portaria.',
  'pergunta_66_resposta_correta':'Decisão judicial transitada em julgado ou processo administrativo disciplinar.',
  'pergunta_66_justificativa':'O servidor estável só perde o cargo por decisão judicial transitada em julgado ou em processo administrativo com ampla defesa.',
  
  'pergunta_67':'A exoneração do servidor efetivo pode ocorrer:',
  'pergunta_67_alternativa_1':'A pedido ou de ofício, quando não satisfeitas as condições do cargo.',
  'pergunta_67_alternativa_2':'Somente a pedido do servidor.',
  'pergunta_67_alternativa_3':'Somente após o estágio probatório.',
  'pergunta_67_alternativa_4':'Mediante decisão do Prefeito, sem justificativa.',
  'pergunta_67_resposta_correta':'A pedido ou de ofício, quando não satisfeitas as condições do cargo.',
  'pergunta_67_justificativa':'A exoneração ocorre a pedido do servidor ou de ofício quando este não satisfaz as condições legais para o cargo.',
  
  'pergunta_68':'A demissão é aplicada ao servidor:',
  'pergunta_68_alternativa_1':'Por conveniência administrativa.',
  'pergunta_68_alternativa_2':'Como penalidade disciplinar prevista em lei.',
  'pergunta_68_alternativa_3':'Por decisão exclusiva do Prefeito.',
  'pergunta_68_alternativa_4':'Mediante pedido fundamentado do chefe imediato.',
  'pergunta_68_resposta_correta':'Como penalidade disciplinar prevista em lei.',
  'pergunta_68_justificativa':'A demissão é a penalidade aplicada em caso de infrações graves cometidas pelo servidor público.',
  
  'pergunta_69':'A readaptação é a forma de provimento que ocorre quando:',
  'pergunta_69_alternativa_1':'O servidor é transferido para outro município.',
  'pergunta_69_alternativa_2':'Há limitação física ou mental que exige adequação a cargo compatível.',
  'pergunta_69_alternativa_3':'O servidor assume função comissionada.',
  'pergunta_69_alternativa_4':'O servidor muda de regime jurídico.',
  'pergunta_69_resposta_correta':'Há limitação física ou mental que exige adequação a cargo compatível.',
  'pergunta_69_justificativa':'A readaptação ocorre quando o servidor sofre limitação que o impede de exercer suas funções originárias.',
  
  'pergunta_70':'O servidor em disponibilidade será:',
  'pergunta_70_alternativa_1':'Exonerado automaticamente após 6 meses.',
  'pergunta_70_alternativa_2':'Aposentado de ofício.',
  'pergunta_70_alternativa_3':'Aproveitado em outro cargo compatível com a remuneração anterior.',
  'pergunta_70_alternativa_4':'Transferido para outro órgão sem necessidade de autorização.',
  'pergunta_70_resposta_correta':'Aproveitado em outro cargo compatível com a remuneração anterior.',
  'pergunta_70_justificativa':'O servidor em disponibilidade será aproveitado em outro cargo compatível, assegurada a remuneração equivalente.',
  
  'pergunta_71':'A reversão ocorre quando:',
  'pergunta_71_alternativa_1':'O servidor retorna à atividade após aposentadoria inválida.',
  'pergunta_71_alternativa_2':'O servidor muda de cargo para outro mais compatível.',
  'pergunta_71_alternativa_3':'O servidor é nomeado novamente após exoneração.',
  'pergunta_71_alternativa_4':'Há mudança de regime jurídico.',
  'pergunta_71_resposta_correta':'O servidor retorna à atividade após aposentadoria inválida.',
  'pergunta_71_justificativa':'A reversão ocorre quando o servidor retorna à atividade após aposentadoria por invalidez que se revela insubsistente.',
  
  'pergunta_72':'A reintegração é o retorno do servidor:',
  'pergunta_72_alternativa_1':'Exonerado por motivo político.',
  'pergunta_72_alternativa_2':'Demitido injustamente, por decisão administrativa ou judicial.',
  'pergunta_72_alternativa_3':'Afastado por interesse pessoal.',
  'pergunta_72_alternativa_4':'Transferido para outro órgão.',
  'pergunta_72_resposta_correta':'Demitido injustamente, por decisão administrativa ou judicial.',
  'pergunta_72_justificativa':'A reintegração é o retorno do servidor demitido ilegalmente ao cargo anteriormente ocupado, com ressarcimento de vencimentos.',
  
  'pergunta_73':'O servidor pode acumular cargos públicos:',
  'pergunta_73_alternativa_1':'Em qualquer hipótese, se houver compatibilidade de horários.',
  'pergunta_73_alternativa_2':'Somente nos casos previstos na Constituição, com compatibilidade de horários.',
  'pergunta_73_alternativa_3':'Quando autorizado pelo Prefeito.',
  'pergunta_73_alternativa_4':'Quando se tratar de cargo em comissão.',
  'pergunta_73_resposta_correta':'Somente nos casos previstos na Constituição, com compatibilidade de horários.',
  'pergunta_73_justificativa':'A acumulação só é permitida nos casos constitucionais e se houver compatibilidade de horários.',
  
  'pergunta_74':'A acumulação ilícita de cargos implica:',
  'pergunta_74_alternativa_1':'Demissão de ambos os cargos.',
  'pergunta_74_alternativa_2':'Obrigação de optar por um dos cargos.',
  'pergunta_74_alternativa_3':'Suspensão por 60 dias.',
  'pergunta_74_alternativa_4':'Advertência escrita.',
  'pergunta_74_resposta_correta':'Obrigação de optar por um dos cargos.',
  'pergunta_74_justificativa':'Identificada a acumulação ilegal, o servidor é notificado para optar por um dos cargos sob pena de demissão.',
  
  'pergunta_75':'O tempo de serviço público é contado para:',
  'pergunta_75_alternativa_1':'Aposentadoria e disponibilidade.',
  'pergunta_75_alternativa_2':'Apenas para férias.',
  'pergunta_75_alternativa_3':'Progressão funcional exclusivamente.',
  'pergunta_75_alternativa_4':'Nenhuma vantagem funcional.',
  'pergunta_75_resposta_correta':'Aposentadoria e disponibilidade.',
  'pergunta_75_justificativa':'O tempo de serviço público é computado para fins de aposentadoria e disponibilidade.',
  
  'pergunta_76':'A licença para tratar de interesses particulares é concedida:',
  'pergunta_76_alternativa_1':'Com vencimento integral.',
  'pergunta_76_alternativa_2':'Sem remuneração, a critério da administração.',
  'pergunta_76_alternativa_3':'Com metade da remuneração.',
  'pergunta_76_alternativa_4':'Apenas após cinco anos de serviço.',
  'pergunta_76_resposta_correta':'Sem remuneração, a critério da administração.',
  'pergunta_76_justificativa':'A licença para tratar de assuntos particulares é concedida sem vencimentos e depende do interesse da administração.',
  
  'pergunta_77':'Durante a licença para tratar de assuntos particulares, o servidor:',
  'pergunta_77_alternativa_1':'Continua recebendo todos os benefícios.',
  'pergunta_77_alternativa_2':'Não conta tempo de serviço.',
  'pergunta_77_alternativa_3':'Mantém o direito a férias.',
  'pergunta_77_alternativa_4':'Pode exercer outro cargo público.',
  'pergunta_77_resposta_correta':'Não conta tempo de serviço.',
  'pergunta_77_justificativa':'Durante a licença para interesse particular, o tempo não é contado para nenhum efeito, salvo disposição legal em contrário.',
  
  'pergunta_78':'A licença para tratamento de saúde será concedida:',
  'pergunta_78_alternativa_1':'Por até 60 dias consecutivos.',
  'pergunta_78_alternativa_2':'Com remuneração, mediante inspeção médica oficial.',
  'pergunta_78_alternativa_3':'Sem vencimentos e a critério do servidor.',
  'pergunta_78_alternativa_4':'Apenas após três anos de serviço.',
  'pergunta_78_resposta_correta':'Com remuneração, mediante inspeção médica oficial.',
  'pergunta_78_justificativa':'A licença médica é concedida com remuneração, desde que comprovada por perícia médica oficial.',
  
  'pergunta_79':'A licença maternidade tem duração de:',
  'pergunta_79_alternativa_1':'90 dias.',
  'pergunta_79_alternativa_2':'120 dias.',
  'pergunta_79_alternativa_3':'150 dias.',
  'pergunta_79_alternativa_4':'180 dias.',
  'pergunta_79_resposta_correta':'120 dias.',
  'pergunta_79_justificativa':'A licença à gestante é de 120 dias, conforme o regime jurídico e a Constituição Federal.',
  
  'pergunta_80':'A licença paternidade é concedida pelo prazo de:',
  'pergunta_80_alternativa_1':'3 dias consecutivos.',
  'pergunta_80_alternativa_2':'5 dias consecutivos.',
  'pergunta_80_alternativa_3':'7 dias consecutivos.',
  'pergunta_80_alternativa_4':'10 dias consecutivos.',
  'pergunta_80_resposta_correta':'5 dias consecutivos.',
  'pergunta_80_justificativa':'A licença paternidade é concedida pelo prazo de 5 dias consecutivos, conforme a Constituição e legislação municipal.',
  
  'pergunta_81':'A contagem do tempo de serviço é interrompida:',
  'pergunta_81_alternativa_1':'Durante férias.',
  'pergunta_81_alternativa_2':'Durante afastamento para mandato eletivo.',
  'pergunta_81_alternativa_3':'Durante licença para tratar de assuntos particulares.',
  'pergunta_81_alternativa_4':'Durante licença por doença em pessoa da família.',
  'pergunta_81_resposta_correta':'Durante licença para tratar de assuntos particulares.',
  'pergunta_81_justificativa':'O tempo de serviço é interrompido durante licenças sem remuneração, como a de interesse particular.',
  
  'pergunta_82':'O servidor terá direito a férias anuais remuneradas de:',
  'pergunta_82_alternativa_1':'20 dias.',
  'pergunta_82_alternativa_2':'25 dias.',
  'pergunta_82_alternativa_3':'30 dias.',
  'pergunta_82_alternativa_4':'35 dias.',
  'pergunta_82_resposta_correta':'30 dias.',
  'pergunta_82_justificativa':'As férias anuais são de 30 dias, conforme previsto no regime jurídico municipal.',
  
  'pergunta_83':'O adicional de férias corresponde a:',
  'pergunta_83_alternativa_1':'10% da remuneração.',
  'pergunta_83_alternativa_2':'20% da remuneração.',
  'pergunta_83_alternativa_3':'1/3 da remuneração.',
  'pergunta_83_alternativa_4':'50% da remuneração.',
  'pergunta_83_resposta_correta':'1/3 da remuneração.',
  'pergunta_83_justificativa':'O servidor tem direito a adicional de 1/3 da remuneração por ocasião das férias, conforme a Constituição Federal.',
  
  'pergunta_84':'As gratificações e adicionais são devidos:',
  'pergunta_84_alternativa_1':'Somente aos servidores efetivos.',
  'pergunta_84_alternativa_2':'Aos servidores efetivos e comissionados, conforme lei específica.',
  'pergunta_84_alternativa_3':'Apenas aos servidores estáveis.',
  'pergunta_84_alternativa_4':'Somente aos servidores aposentados.',
  'pergunta_84_resposta_correta':'Aos servidores efetivos e comissionados, conforme lei específica.',
  'pergunta_84_justificativa':'As gratificações e adicionais são concedidos de acordo com a legislação municipal que rege cada categoria.',
  
  'pergunta_85':'O vencimento do cargo efetivo é irredutível, salvo:',
  'pergunta_85_alternativa_1':'Por decisão judicial.',
  'pergunta_85_alternativa_2':'Por interesse do servidor.',
  'pergunta_85_alternativa_3':'Quando houver alteração de carga horária prevista em lei.',
  'pergunta_85_alternativa_4':'Por ato do Prefeito.',
  'pergunta_85_resposta_correta':'Quando houver alteração de carga horária prevista em lei.',
  'pergunta_85_justificativa':'A irredutibilidade do vencimento admite exceção apenas quando houver alteração legal na jornada de trabalho.',
  
  'pergunta_86':'As vantagens pessoais incorporam-se à remuneração do servidor:',
  'pergunta_86_alternativa_1':'Em qualquer hipótese.',
  'pergunta_86_alternativa_2':'Apenas quando previstas em lei.',
  'pergunta_86_alternativa_3':'Por decisão do chefe imediato.',
  'pergunta_86_alternativa_4':'A critério do Prefeito.',
  'pergunta_86_resposta_correta':'Apenas quando previstas em lei.',
  'pergunta_86_justificativa':'Somente as vantagens expressamente previstas em lei podem ser incorporadas à remuneração.',
  
  'pergunta_87':'O regime jurídico assegura ao servidor o direito de petição:',
  'pergunta_87_alternativa_1':'Somente em casos de punição disciplinar.',
  'pergunta_87_alternativa_2':'Em defesa de direito ou contra ilegalidade.',
  'pergunta_87_alternativa_3':'Apenas por via judicial.',
  'pergunta_87_alternativa_4':'Mediante autorização do superior.',
  'pergunta_87_resposta_correta':'Em defesa de direito ou contra ilegalidade.',
  'pergunta_87_justificativa':'O direito de petição é garantido ao servidor para defesa de direitos e contra atos ilegais ou abusivos.',
  
  'pergunta_88':'A responsabilidade do servidor pode ser:',
  'pergunta_88_alternativa_1':'Administrativa, civil e penal.',
  'pergunta_88_alternativa_2':'Apenas administrativa.',
  'pergunta_88_alternativa_3':'Somente civil.',
  'pergunta_88_alternativa_4':'Exclusivamente penal.',
  'pergunta_88_resposta_correta':'Administrativa, civil e penal.',
  'pergunta_88_justificativa':'O servidor responde nas esferas administrativa, civil e penal pelos atos praticados no exercício de suas funções.',
  
  'pergunta_89':'A responsabilidade civil decorre de:',
  'pergunta_89_alternativa_1':'Dano causado a particular ou à Administração.',
  'pergunta_89_alternativa_2':'Infração disciplinar interna.',
  'pergunta_89_alternativa_3':'Descumprimento de ordem hierárquica.',
  'pergunta_89_alternativa_4':'Acúmulo de função pública.',
  'pergunta_89_resposta_correta':'Dano causado a particular ou à Administração.',
  'pergunta_89_justificativa':'O servidor é civilmente responsável por prejuízo causado a terceiros ou ao erário.',
  
  'pergunta_90':'A responsabilidade penal do servidor decorre de:',
  'pergunta_90_alternativa_1':'Ato lesivo ao erário ou crime praticado no exercício da função.',
  'pergunta_90_alternativa_2':'Descumprimento de horário.',
  'pergunta_90_alternativa_3':'Falta leve.',
  'pergunta_90_alternativa_4':'Reprovação em estágio probatório.',
  'pergunta_90_resposta_correta':'Ato lesivo ao erário ou crime praticado no exercício da função.',
  'pergunta_90_justificativa':'A responsabilidade penal decorre de crimes cometidos no exercício do cargo ou em razão dele.',
  
  'pergunta_91':'A responsabilidade administrativa decorre de:',
  'pergunta_91_alternativa_1':'Infração de dever funcional previsto em lei.',
  'pergunta_91_alternativa_2':'Danos causados ao erário apenas.',
  'pergunta_91_alternativa_3':'Decisão judicial transitada em julgado.',
  'pergunta_91_alternativa_4':'Pedido do superior hierárquico.',
  'pergunta_91_resposta_correta':'Infração de dever funcional previsto em lei.',
  'pergunta_91_justificativa':'A responsabilidade administrativa é aquela decorrente de infração aos deveres funcionais do servidor.',
  
  'pergunta_92':'As penalidades disciplinares aplicáveis são:',
  'pergunta_92_alternativa_1':'Advertência, suspensão e demissão.',
  'pergunta_92_alternativa_2':'Advertência, multa e rescisão.',
  'pergunta_92_alternativa_3':'Suspensão, cassação e exoneração.',
  'pergunta_92_alternativa_4':'Advertência, transferência e rescisão.',
  'pergunta_92_resposta_correta':'Advertência, suspensão e demissão.',
  'pergunta_92_justificativa':'São penalidades disciplinares previstas no regime jurídico: advertência, suspensão e demissão.',
  
  'pergunta_93':'A pena de advertência será aplicada:',
  'pergunta_93_alternativa_1':'Por falta leve e registrada nos assentamentos funcionais.',
  'pergunta_93_alternativa_2':'Por falta grave.',
  'pergunta_93_alternativa_3':'Por reincidência em falta grave.',
  'pergunta_93_alternativa_4':'Apenas após processo administrativo.',
  'pergunta_93_resposta_correta':'Por falta leve e registrada nos assentamentos funcionais.',
  'pergunta_93_justificativa':'A advertência é aplicada por falta leve e deve constar nos assentamentos do servidor.',
  
  'pergunta_94':'A suspensão será aplicada quando:',
  'pergunta_94_alternativa_1':'Houver reincidência em falta leve ou cometimento de falta grave.',
  'pergunta_94_alternativa_2':'O servidor faltar um dia ao serviço.',
  'pergunta_94_alternativa_3':'O servidor atrasar-se ocasionalmente.',
  'pergunta_94_alternativa_4':'Por qualquer infração funcional.',
  'pergunta_94_resposta_correta':'Houver reincidência em falta leve ou cometimento de falta grave.',
  'pergunta_94_justificativa':'A suspensão é aplicada em casos de reincidência em falta leve ou em faltas graves.',
  
  'pergunta_95':'A demissão será aplicada ao servidor que:',
  'pergunta_95_alternativa_1':'Cometer improbidade administrativa.',
  'pergunta_95_alternativa_2':'Atrasar-se por cinco dias.',
  'pergunta_95_alternativa_3':'Recusar-se a participar de curso.',
  'pergunta_95_alternativa_4':'Cometer infração leve.',
  'pergunta_95_resposta_correta':'Cometer improbidade administrativa.',
  'pergunta_95_justificativa':'A demissão é a penalidade máxima e é aplicada em casos graves, como improbidade e crime contra a administração pública.',
  
  'pergunta_96':'O servidor que causar prejuízo ao erário deverá:',
  'pergunta_96_alternativa_1':'Ser apenas advertido.',
  'pergunta_96_alternativa_2':'Ressarcir o dano, independentemente de outras penalidades.',
  'pergunta_96_alternativa_3':'Ser transferido de cargo.',
  'pergunta_96_alternativa_4':'Perder automaticamente a função.',
  'pergunta_96_resposta_correta':'Ressarcir o dano, independentemente de outras penalidades.',
  'pergunta_96_justificativa':'O servidor responde pelo ressarcimento de danos causados à Administração, além das penalidades cabíveis.',
  
  'pergunta_97':'O processo administrativo disciplinar assegura:',
  'pergunta_97_alternativa_1':'Ampla defesa e contraditório.',
  'pergunta_97_alternativa_2':'Somente direito de defesa escrita.',
  'pergunta_97_alternativa_3':'Apenas manifestação oral.',
  'pergunta_97_alternativa_4':'Julgamento sumário.',
  'pergunta_97_resposta_correta':'Ampla defesa e contraditório.',
  'pergunta_97_justificativa':'O servidor tem direito à ampla defesa e ao contraditório em qualquer processo administrativo.',
  
  'pergunta_98':'O prazo prescricional para a ação disciplinar começa a contar:',
  'pergunta_98_alternativa_1':'Da data da infração.',
  'pergunta_98_alternativa_2':'Da data do conhecimento do fato pela autoridade competente.',
  'pergunta_98_alternativa_3':'Do término do processo administrativo.',
  'pergunta_98_alternativa_4':'Da comunicação ao servidor.',
  'pergunta_98_resposta_correta':'Da data do conhecimento do fato pela autoridade competente.',
  'pergunta_98_justificativa':'A contagem do prazo prescricional inicia-se quando a autoridade competente toma ciência da infração.',
  
  'pergunta_99':'O servidor poderá ser afastado preventivamente:',
  'pergunta_99_alternativa_1':'Por até 60 dias, prorrogáveis por igual período, quando necessário à apuração de infração.',
  'pergunta_99_alternativa_2':'Por tempo indeterminado, até conclusão do processo.',
  'pergunta_99_alternativa_3':'Por decisão judicial apenas.',
  'pergunta_99_alternativa_4':'A critério do superior imediato.',
  'pergunta_99_resposta_correta':'Por até 60 dias, prorrogáveis por igual período, quando necessário à apuração de infração.',
  'pergunta_99_justificativa':'O afastamento preventivo visa garantir a lisura do processo disciplinar, sendo limitado a 60 dias prorrogáveis.',
  
  'pergunta_100':'O servidor responde pelos seus atos perante:',
  'pergunta_100_alternativa_1':'Apenas a administração municipal.',
  'pergunta_100_alternativa_2':'A administração, o Poder Judiciário e terceiros prejudicados.',
  'pergunta_100_alternativa_3':'Somente a corregedoria.',
  'pergunta_100_alternativa_4':'Somente o Tribunal de Contas.',
  'pergunta_100_resposta_correta':'A administração, o Poder Judiciário e terceiros prejudicados.',
  'pergunta_100_justificativa':'O servidor é responsável por seus atos nas esferas administrativa, civil e penal, inclusive perante terceiros prejudicados.',
  

'pergunta_101':'De acordo com a Lei Complementar nº 3.673/91, quem é considerado servidor público municipal?',
    'pergunta_101_alternativa_1':'Qualquer pessoa que trabalhe para o Município, mesmo sem vínculo formal.',
    'pergunta_101_alternativa_2':'A pessoa legalmente investida em cargo público.',
    'pergunta_101_alternativa_3':'A pessoa que exerce função pública temporária.',
    'pergunta_101_alternativa_4':'Somente os ocupantes de cargos em comissão.',
    'pergunta_101_resposta_correta':'A pessoa legalmente investida em cargo público.',
    'pergunta_101_justificativa':'Segundo o art. 2º da Lei Complementar nº 3.673/91, servidor é a pessoa legalmente investida em cargo público.',
    //----------------------------------
    'pergunta_102':'O que é considerado cargo público, conforme o Estatuto dos Servidores Municipais?',
    'pergunta_102_alternativa_1':'A função de confiança exercida temporariamente.',
    'pergunta_102_alternativa_2':'O emprego de natureza celetista.',
    'pergunta_102_alternativa_3':'O conjunto de atribuições e responsabilidades cometidas ao servidor público, criado por lei e remunerado pelos cofres municipais.',
    'pergunta_102_alternativa_4':'O posto de trabalho designado por contrato administrativo.',
    'pergunta_102_resposta_correta':'O conjunto de atribuições e responsabilidades cometidas ao servidor público, criado por lei e remunerado pelos cofres municipais.',
    'pergunta_102_justificativa':'De acordo com o art. 3º da LC 3.673/91, cargo público é o criado por lei, em número certo, remunerado pelos cofres municipais.',
    //----------------------------------
    'pergunta_103':'A investidura em cargo público depende obrigatoriamente de:',
    'pergunta_103_alternativa_1':'Nomeação direta pelo Prefeito.',
    'pergunta_103_alternativa_2':'Indicação de autoridade competente.',
    'pergunta_103_alternativa_3':'Aprovação prévia em concurso público de provas ou de provas e títulos.',
    'pergunta_103_alternativa_4':'Curso de formação na Escola de Governo Municipal.',
    'pergunta_103_resposta_correta':'Aprovação prévia em concurso público de provas ou de provas e títulos.',
    'pergunta_103_justificativa':'O art. 4º da LC 3.673/91 determina que a investidura em cargo público depende de aprovação prévia em concurso público.',
    //----------------------------------
    'pergunta_104':'O prazo de validade de um concurso público municipal é de até:',
    'pergunta_104_alternativa_1':'1 ano, improrrogável.',
    'pergunta_104_alternativa_2':'2 anos, prorrogável uma vez por igual período.',
    'pergunta_104_alternativa_3':'3 anos, prorrogável uma vez por igual período.',
    'pergunta_104_alternativa_4':'5 anos, improrrogável.',
    'pergunta_104_resposta_correta':'2 anos, prorrogável uma vez por igual período.',
    'pergunta_104_justificativa':'Conforme o art. 15, III, o prazo de validade do concurso é de até dois anos, prorrogável uma vez por igual período.',
    //----------------------------------
    'pergunta_105':'Posse é definida como:',
    'pergunta_105_alternativa_1':'A nomeação para cargo público.',
    'pergunta_105_alternativa_2':'A entrada em exercício das funções.',
    'pergunta_105_alternativa_3':'A aceitação expressa das atribuições, deveres e responsabilidades do cargo, formalizada por termo.',
    'pergunta_105_alternativa_4':'O início das atividades laborais na repartição.',
    'pergunta_105_resposta_correta':'A aceitação expressa das atribuições, deveres e responsabilidades do cargo, formalizada por termo.',
    'pergunta_105_justificativa':'O art. 17 da LC 3.673/91 define posse como a aceitação expressa das atribuições do cargo, formalizada por termo.',
    //----------------------------------
    'pergunta_106':'O prazo para tomar posse é de quantos dias após a publicação do ato de provimento?',
    'pergunta_106_alternativa_1':'10 dias, improrrogáveis.',
    'pergunta_106_alternativa_2':'15 dias, prorrogáveis por mais 15 a pedido.',
    'pergunta_106_alternativa_3':'20 dias, prorrogáveis uma vez.',
    'pergunta_106_alternativa_4':'30 dias, sem prorrogação.',
    'pergunta_106_resposta_correta':'15 dias, prorrogáveis por mais 15 a pedido.',
    'pergunta_106_justificativa':'O §1º do art. 17 estabelece o prazo de 15 dias para a posse, prorrogável por igual período a requerimento.',
    //----------------------------------
    'pergunta_107':'O servidor se torna estável após:',
    'pergunta_107_alternativa_1':'Dois anos de efetivo exercício.',
    'pergunta_107_alternativa_2':'Três anos de efetivo exercício e avaliação especial de desempenho.',
    'pergunta_107_alternativa_3':'Quatro anos de efetivo exercício e aprovação em estágio probatório.',
    'pergunta_107_alternativa_4':'Cinco anos de serviço público contínuo.',
    'pergunta_107_resposta_correta':'Três anos de efetivo exercício e avaliação especial de desempenho.',
    'pergunta_107_justificativa':'Conforme art. 32 da LC 3.673/91, a estabilidade é adquirida após três anos e mediante avaliação especial.',
    //----------------------------------
    'pergunta_108':'Durante o estágio probatório, o servidor será avaliado, entre outros fatores, por:',
    'pergunta_108_alternativa_1':'Assiduidade, responsabilidade e produtividade.',
    'pergunta_108_alternativa_2':'Pontualidade, relacionamento interpessoal e iniciativa.',
    'pergunta_108_alternativa_3':'Ambas as alternativas anteriores.',
    'pergunta_108_alternativa_4':'Somente disciplina e eficiência.',
    'pergunta_108_resposta_correta':'Ambas as alternativas anteriores.',
    'pergunta_108_justificativa':'O art. 42 indica os fatores de avaliação: assiduidade, disciplina, responsabilidade, produtividade, relacionamento interpessoal, iniciativa, entre outros.',
    //----------------------------------
    'pergunta_109':'O servidor em estágio probatório NÃO pode:',
    'pergunta_109_alternativa_1':'Solicitar férias regulamentares.',
    'pergunta_109_alternativa_2':'Ser cedido ou colocado à disposição de outros órgãos públicos.',
    'pergunta_109_alternativa_3':'Participar de cursos de capacitação.',
    'pergunta_109_alternativa_4':'Ser avaliado em mais de um fator.',
    'pergunta_109_resposta_correta':'Ser cedido ou colocado à disposição de outros órgãos públicos.',
    'pergunta_109_justificativa':'O §5º do art. 45 da LC 3.673/91 veda a cessão de servidor em estágio probatório.',
    //----------------------------------
    'pergunta_110':'O servidor será exonerado do estágio probatório quando:',
    'pergunta_110_alternativa_1':'Deixar de apresentar relatórios de desempenho.',
    'pergunta_110_alternativa_2':'Não atingir a pontuação mínima exigida nos fatores de avaliação.',
    'pergunta_110_alternativa_3':'Solicitar transferência de setor.',
    'pergunta_110_alternativa_4':'Completar dois anos de estágio.',
    'pergunta_110_resposta_correta':'Não atingir a pontuação mínima exigida nos fatores de avaliação.',
    'pergunta_110_justificativa':'O art. 45-A prevê a exoneração do servidor que não atingir a pontuação mínima exigida.',
    //----------------------------------
    'pergunta_111':'Qual é a forma de provimento que consiste no retorno do aposentado à atividade?',
    'pergunta_111_alternativa_1':'Reintegração',
    'pergunta_111_alternativa_2':'Reversão',
    'pergunta_111_alternativa_3':'Aproveitamento',
    'pergunta_111_alternativa_4':'Recondução',
    'pergunta_111_resposta_correta':'Reversão',
    'pergunta_111_justificativa':'De acordo com o art. 39, reversão é o retorno do aposentado à atividade, quando verificado que não subsistem os motivos da aposentadoria.',
    //----------------------------------
    'pergunta_112':'Readaptação ocorre quando:',
    'pergunta_112_alternativa_1':'O servidor muda de cargo por promoção.',
    'pergunta_112_alternativa_2':'O servidor é transferido para outro município.',
    'pergunta_112_alternativa_3':'O servidor é investido em cargo de igual padrão, mais compatível com sua aptidão ou vocação.',
    'pergunta_112_alternativa_4':'O servidor é reintegrado após demissão indevida.',
    'pergunta_112_resposta_correta':'O servidor é investido em cargo de igual padrão, mais compatível com sua aptidão ou vocação.',
    'pergunta_112_justificativa':'O art. 34 define readaptação como a investidura do servidor em cargo compatível com sua aptidão ou vocação.',
    //----------------------------------
    'pergunta_113':'Reintegração é o reingresso no serviço público de servidor:',
    'pergunta_113_alternativa_1':'Aposentado compulsoriamente.',
    'pergunta_113_alternativa_2':'Demitido ou exonerado, com ressarcimento das vantagens do cargo.',
    'pergunta_113_alternativa_3':'Que retornou após licença.',
    'pergunta_113_alternativa_4':'Que foi removido de ofício.',
    'pergunta_113_resposta_correta':'Demitido ou exonerado, com ressarcimento das vantagens do cargo.',
    'pergunta_113_justificativa':'Segundo o art. 48, a reintegração é o reingresso do servidor demitido ou exonerado, com ressarcimento das vantagens.',
    //----------------------------------
    'pergunta_114':'O servidor estável só perderá o cargo:',
    'pergunta_114_alternativa_1':'Por decisão política do Prefeito.',
    'pergunta_114_alternativa_2':'Por decisão administrativa, sem defesa.',
    'pergunta_114_alternativa_3':'Por sentença judicial transitada em julgado ou decisão em processo administrativo disciplinar com ampla defesa.',
    'pergunta_114_alternativa_4':'Por decisão da chefia imediata.',
    'pergunta_114_resposta_correta':'Por sentença judicial transitada em julgado ou decisão em processo administrativo disciplinar com ampla defesa.',
    'pergunta_114_justificativa':'Art. 33: o servidor estável só perderá o cargo nessas hipóteses.',
    //----------------------------------
    'pergunta_115':'Quem tem competência para dar posse aos servidores municipais?',
    'pergunta_115_alternativa_1':'Somente o Prefeito.',
    'pergunta_115_alternativa_2':'O Prefeito, Secretários Municipais e dirigentes de autarquias e fundações.',
    'pergunta_115_alternativa_3':'A Câmara Municipal.',
    'pergunta_115_alternativa_4':'A Procuradoria-Geral do Município.',
    'pergunta_115_resposta_correta':'O Prefeito, Secretários Municipais e dirigentes de autarquias e fundações.',
    'pergunta_115_justificativa':'O art. 18 da LC 3.673/91 define os competentes para dar posse.',
    //----------------------------------
      //----------------------------------
  'pergunta_116':'O servidor poderá afastar-se do cargo, sem perda de vencimento, para exercer mandato eletivo:',
  'pergunta_116_alternativa_1':'Apenas se for vereador no mesmo município.',
  'pergunta_116_alternativa_2':'Nos casos de mandato federal, estadual ou municipal, conforme previsto em lei.',
  'pergunta_116_alternativa_3':'Somente para mandato de Prefeito.',
  'pergunta_116_alternativa_4':'Exclusivamente para cargos federais.',
  'pergunta_116_resposta_correta':'Nos casos de mandato federal, estadual ou municipal, conforme previsto em lei.',
  'pergunta_116_justificativa':'A LC 3.673/91 assegura afastamento do cargo ao servidor eleito para mandato eletivo, conforme previsto na Constituição Federal.',
  //----------------------------------
  'pergunta_117':'Qual é o prazo máximo de licença remunerada para tratamento de saúde de pessoa da família?',
  'pergunta_117_alternativa_1':'30 dias.',
  'pergunta_117_alternativa_2':'60 dias.',
  'pergunta_117_alternativa_3':'90 dias.',
  'pergunta_117_alternativa_4':'120 dias.',
  'pergunta_117_resposta_correta':'90 dias.',
  'pergunta_117_justificativa':'O art. 90 da LC 3.673/91 prevê licença de até 90 dias com vencimentos integrais, para cuidar de pessoa da família.',
  //----------------------------------
  'pergunta_118':'Durante a licença-gestante, a servidora faz jus a:',
  'pergunta_118_alternativa_1':'90 dias de licença com remuneração integral.',
  'pergunta_118_alternativa_2':'120 dias de licença com remuneração integral.',
  'pergunta_118_alternativa_3':'150 dias de licença sem remuneração.',
  'pergunta_118_alternativa_4':'60 dias de licença com vencimentos parciais.',
  'pergunta_118_resposta_correta':'120 dias de licença com remuneração integral.',
  'pergunta_118_justificativa':'Conforme o art. 95, a servidora tem direito a 120 dias de licença-maternidade, com vencimentos integrais.',
  //----------------------------------
  'pergunta_119':'O servidor poderá faltar ao serviço sem prejuízo da remuneração:',
  'pergunta_119_alternativa_1':'Por até 2 dias consecutivos por motivo de casamento.',
  'pergunta_119_alternativa_2':'Por até 7 dias consecutivos por motivo de falecimento de cônjuge, pais, filhos ou irmãos.',
  'pergunta_119_alternativa_3':'Por até 3 dias consecutivos por falecimento de tios e primos.',
  'pergunta_119_alternativa_4':'Por até 10 dias consecutivos por casamento.',
  'pergunta_119_resposta_correta':'Por até 7 dias consecutivos por motivo de falecimento de cônjuge, pais, filhos ou irmãos.',
  'pergunta_119_justificativa':'O art. 102 assegura até 7 dias consecutivos de licença nesses casos, sem prejuízo dos vencimentos.',
  //----------------------------------
  'pergunta_120':'O servidor público municipal tem o dever de:',
  'pergunta_120_alternativa_1':'Atuar apenas sob ordens diretas do Prefeito.',
  'pergunta_120_alternativa_2':'Cumprir ordens manifestamente ilegais.',
  'pergunta_120_alternativa_3':'Exercer com zelo e dedicação as atribuições do cargo.',
  'pergunta_120_alternativa_4':'Ignorar instruções de superiores hierárquicos.',
  'pergunta_120_resposta_correta':'Exercer com zelo e dedicação as atribuições do cargo.',
  'pergunta_120_justificativa':'Conforme o art. 113, o servidor deve exercer com zelo e dedicação as atribuições do cargo.',
  //----------------------------------
  'pergunta_121':'É proibido ao servidor público municipal:',
  'pergunta_121_alternativa_1':'Participar de concursos públicos.',
  'pergunta_121_alternativa_2':'Aceitar representação de Estado estrangeiro sem autorização.',
  'pergunta_121_alternativa_3':'Solicitar férias regulamentares.',
  'pergunta_121_alternativa_4':'Usar crachá de identificação no trabalho.',
  'pergunta_121_resposta_correta':'Aceitar representação de Estado estrangeiro sem autorização.',
  'pergunta_121_justificativa':'O art. 115, inciso I, proíbe expressamente que o servidor aceite representação de Estado estrangeiro sem autorização.',
  //----------------------------------
  'pergunta_122':'O servidor responde civil, penal e administrativamente pelo exercício irregular de suas atribuições. Essa responsabilidade é:',
  'pergunta_122_alternativa_1':'Dependente uma da outra.',
  'pergunta_122_alternativa_2':'Independente entre si, podendo acumular-se.',
  'pergunta_122_alternativa_3':'Apenas penal.',
  'pergunta_122_alternativa_4':'Apenas administrativa.',
  'pergunta_122_resposta_correta':'Independente entre si, podendo acumular-se.',
  'pergunta_122_justificativa':'Conforme o art. 129, as sanções civis, penais e administrativas são independentes e podem acumular-se.',
  //----------------------------------
  'pergunta_123':'A pena de advertência será aplicada:',
  'pergunta_123_alternativa_1':'Verbalmente, por pequena falta funcional.',
  'pergunta_123_alternativa_2':'Por escrito, quando a falta for leve e não justificar penalidade mais grave.',
  'pergunta_123_alternativa_3':'Somente após sindicância.',
  'pergunta_123_alternativa_4':'Apenas em caso de reincidência.',
  'pergunta_123_resposta_correta':'Por escrito, quando a falta for leve e não justificar penalidade mais grave.',
  'pergunta_123_justificativa':'O art. 139 define que a advertência é aplicada por escrito, em casos de pequenas faltas.',
  //----------------------------------
  'pergunta_124':'A pena de suspensão poderá ser convertida em multa:',
  'pergunta_124_alternativa_1':'Quando o servidor solicitar.',
  'pergunta_124_alternativa_2':'Quando houver conveniência para o serviço público.',
  'pergunta_124_alternativa_3':'Mediante aprovação da Câmara Municipal.',
  'pergunta_124_alternativa_4':'Em nenhuma hipótese.',
  'pergunta_124_resposta_correta':'Quando houver conveniência para o serviço público.',
  'pergunta_124_justificativa':'Conforme o art. 141, a suspensão poderá ser convertida em multa se houver conveniência para o serviço.',
  //----------------------------------
  'pergunta_125':'A demissão será aplicada ao servidor que:',
  'pergunta_125_alternativa_1':'For reincidente em faltas leves.',
  'pergunta_125_alternativa_2':'Abandonar o cargo por mais de 30 dias consecutivos sem justificativa.',
  'pergunta_125_alternativa_3':'Chegar atrasado mais de cinco vezes ao mês.',
  'pergunta_125_alternativa_4':'Deixar de assinar o ponto uma vez.',
  'pergunta_125_resposta_correta':'Abandonar o cargo por mais de 30 dias consecutivos sem justificativa.',
  'pergunta_125_justificativa':'O art. 143 prevê a demissão em caso de abandono de cargo por mais de 30 dias consecutivos.',
  //----------------------------------
  'pergunta_126':'O processo administrativo disciplinar deverá ser concluído no prazo máximo de:',
  'pergunta_126_alternativa_1':'20 dias.',
  'pergunta_126_alternativa_2':'30 dias.',
  'pergunta_126_alternativa_3':'60 dias, prorrogáveis por igual período.',
  'pergunta_126_alternativa_4':'90 dias, improrrogáveis.',
  'pergunta_126_resposta_correta':'60 dias, prorrogáveis por igual período.',
  'pergunta_126_justificativa':'O art. 155 estabelece o prazo de 60 dias para conclusão do processo, prorrogável por igual período.',
  //----------------------------------
  'pergunta_127':'Durante o processo administrativo disciplinar, é assegurado ao acusado:',
  'pergunta_127_alternativa_1':'Apenas o direito de ser ouvido uma vez.',
  'pergunta_127_alternativa_2':'Ampla defesa e contraditório.',
  'pergunta_127_alternativa_3':'Sigilo total do processo.',
  'pergunta_127_alternativa_4':'Apenas acompanhamento do advogado do Município.',
  'pergunta_127_resposta_correta':'Ampla defesa e contraditório.',
  'pergunta_127_justificativa':'O art. 153 assegura ao acusado o direito à ampla defesa e ao contraditório.',
  //----------------------------------
  'pergunta_128':'A revisão do processo disciplinar poderá ser requerida:',
  'pergunta_128_alternativa_1':'A qualquer tempo, quando surgirem fatos novos.',
  'pergunta_128_alternativa_2':'Somente até 5 anos após a decisão.',
  'pergunta_128_alternativa_3':'Apenas pelo servidor punido.',
  'pergunta_128_alternativa_4':'Somente com autorização do Prefeito.',
  'pergunta_128_resposta_correta':'A qualquer tempo, quando surgirem fatos novos.',
  'pergunta_128_justificativa':'O art. 166 permite a revisão do processo a qualquer tempo, quando houver fatos novos ou circunstâncias relevantes.',
  //----------------------------------
  'pergunta_129':'A sindicância tem por finalidade:',
  'pergunta_129_alternativa_1':'Apenas punir o servidor.',
  'pergunta_129_alternativa_2':'Apurar irregularidades leves ou preliminarmente verificar a existência de falta funcional.',
  'pergunta_129_alternativa_3':'Substituir o processo disciplinar.',
  'pergunta_129_alternativa_4':'Exonerar servidores estáveis.',
  'pergunta_129_resposta_correta':'Apurar irregularidades leves ou preliminarmente verificar a existência de falta funcional.',
  'pergunta_129_justificativa':'A sindicância tem caráter investigativo e visa apurar irregularidades antes da abertura de processo disciplinar.',
  //----------------------------------
  'pergunta_130':'O servidor estável poderá ser reconduzido ao cargo anterior quando:',
  'pergunta_130_alternativa_1':'For exonerado a pedido.',
  'pergunta_130_alternativa_2':'For inabilitado em estágio probatório de novo cargo.',
  'pergunta_130_alternativa_3':'Sofrer penalidade de suspensão.',
  'pergunta_130_alternativa_4':'For promovido.',
  'pergunta_130_resposta_correta':'For inabilitado em estágio probatório de novo cargo.',
  'pergunta_130_justificativa':'Art. 46: recondução ocorre quando o servidor é inabilitado no estágio probatório de outro cargo.',
  //----------------------------------
  'pergunta_131':'O servidor tem direito a férias anuais remuneradas com adicional de:',
  'pergunta_131_alternativa_1':'10% sobre o vencimento.',
  'pergunta_131_alternativa_2':'Um terço a mais do valor do cargo.',
  'pergunta_131_alternativa_3':'Metade do vencimento.',
  'pergunta_131_alternativa_4':'Sem adicional.',
  'pergunta_131_resposta_correta':'Um terço a mais do valor do cargo.',
  'pergunta_131_justificativa':'O art. 83 assegura férias anuais com adicional de 1/3 do vencimento.',
  //----------------------------------
  'pergunta_132':'O servidor poderá acumular cargos públicos apenas quando:',
  'pergunta_132_alternativa_1':'Ambos forem de nível médio.',
  'pergunta_132_alternativa_2':'Houver compatibilidade de horários e previsão legal.',
  'pergunta_132_alternativa_3':'For autorizado pelo Prefeito.',
  'pergunta_132_alternativa_4':'Um dos cargos for em comissão.',
  'pergunta_132_resposta_correta':'Houver compatibilidade de horários e previsão legal.',
  'pergunta_132_justificativa':'Art. 78: é permitida a acumulação nas hipóteses constitucionais, com compatibilidade de horários.',
  //----------------------------------
  'pergunta_133':'O tempo de serviço público prestado ao Município será contado para:',
  'pergunta_133_alternativa_1':'Somente para aposentadoria.',
  'pergunta_133_alternativa_2':'Todos os efeitos legais, salvo disposição em contrário.',
  'pergunta_133_alternativa_3':'Apenas para promoção.',
  'pergunta_133_alternativa_4':'Somente para férias e licença-prêmio.',
  'pergunta_133_resposta_correta':'Todos os efeitos legais, salvo disposição em contrário.',
  'pergunta_133_justificativa':'O art. 81 dispõe que o tempo de serviço público é contado para todos os efeitos legais.',
  //----------------------------------
  'pergunta_134':'Qual é o prazo para o servidor entrar em exercício após a posse?',
  'pergunta_134_alternativa_1':'5 dias.',
  'pergunta_134_alternativa_2':'10 dias.',
  'pergunta_134_alternativa_3':'15 dias.',
  'pergunta_134_alternativa_4':'20 dias.',
  'pergunta_134_resposta_correta':'10 dias.',
  'pergunta_134_justificativa':'Conforme o art. 20, o servidor deve entrar em exercício no prazo de até 10 dias após a posse.',
  //----------------------------------
  'pergunta_135':'O servidor poderá ser removido:',
  'pergunta_135_alternativa_1':'Apenas a pedido.',
  'pergunta_135_alternativa_2':'De ofício ou a pedido, conforme o interesse do serviço.',
  'pergunta_135_alternativa_3':'Somente com autorização do Prefeito.',
  'pergunta_135_alternativa_4':'Apenas para outro município.',
  'pergunta_135_resposta_correta':'De ofício ou a pedido, conforme o interesse do serviço.',
  'pergunta_135_justificativa':'O art. 50 define que a remoção pode ocorrer de ofício ou a pedido, de acordo com a conveniência administrativa.',
  //----------------------------------
  'pergunta_136':'O servidor poderá obter licença para tratar de interesses particulares:',
  'pergunta_136_alternativa_1':'Por até 90 dias, com vencimento.',
  'pergunta_136_alternativa_2':'Por até 2 anos, sem remuneração.',
  'pergunta_136_alternativa_3':'Por prazo indeterminado, com vencimento.',
  'pergunta_136_alternativa_4':'Apenas durante férias coletivas.',
  'pergunta_136_resposta_correta':'Por até 2 anos, sem remuneração.',
  'pergunta_136_justificativa':'O art. 99 prevê licença de até dois anos, sem vencimentos, para tratar de assuntos particulares.',
  //----------------------------------
  'pergunta_137':'Qual é a penalidade aplicável ao servidor que praticar usura?',
  'pergunta_137_alternativa_1':'Advertência.',
  'pergunta_137_alternativa_2':'Suspensão.',
  'pergunta_137_alternativa_3':'Demissão.',
  'pergunta_137_alternativa_4':'Multa.',
  'pergunta_137_resposta_correta':'Demissão.',
  'pergunta_137_justificativa':'O art. 115, III, proíbe a prática de usura, sendo punida com demissão em caso de comprovação.',
  //----------------------------------
  'pergunta_138':'É direito do servidor público municipal:',
  'pergunta_138_alternativa_1':'Receber vencimento inferior ao salário mínimo.',
  'pergunta_138_alternativa_2':'Perceber vencimento fixado em lei, nunca inferior ao salário mínimo.',
  'pergunta_138_alternativa_3':'Apenas salário base, sem adicionais.',
  'pergunta_138_alternativa_4':'Somente gratificações.',
  'pergunta_138_resposta_correta':'Perceber vencimento fixado em lei, nunca inferior ao salário mínimo.',
  'pergunta_138_justificativa':'O art. 76 garante vencimento nunca inferior ao salário mínimo.',
  //----------------------------------
  'pergunta_139':'O servidor que sofrer acidente em serviço terá direito a:',
  'pergunta_139_alternativa_1':'Licença especial com vencimentos integrais.',
  'pergunta_139_alternativa_2':'Licença sem vencimentos.',
  'pergunta_139_alternativa_3':'Apenas auxílio-doença.',
  'pergunta_139_alternativa_4':'Suspensão do contrato.',
  'pergunta_139_resposta_correta':'Licença especial com vencimentos integrais.',
  'pergunta_139_justificativa':'O art. 97 prevê licença especial com vencimentos integrais em caso de acidente em serviço.',
  //----------------------------------
  'pergunta_140':'Qual é o efeito da absolvição criminal sobre a responsabilidade administrativa do servidor?',
  'pergunta_140_alternativa_1':'Afasta toda responsabilidade administrativa.',
  'pergunta_140_alternativa_2':'Afasta apenas quando negar a existência do fato ou sua autoria.',
  'pergunta_140_alternativa_3':'Não produz qualquer efeito.',
  'pergunta_140_alternativa_4':'Depende de autorização judicial.',
  'pergunta_140_resposta_correta':'Afasta apenas quando negar a existência do fato ou sua autoria.',
  'pergunta_140_justificativa':'Conforme o art. 130, a absolvição criminal afasta a responsabilidade administrativa somente quando negar o fato ou autoria.',
  //----------------------------------
  'pergunta_141':'Qual o prazo máximo de afastamento por suspensão?',
  'pergunta_141_alternativa_1':'15 dias.',
  'pergunta_141_alternativa_2':'30 dias.',
  'pergunta_141_alternativa_3':'60 dias.',
  'pergunta_141_alternativa_4':'90 dias.',
  'pergunta_141_resposta_correta':'60 dias.',
  'pergunta_141_justificativa':'O art. 141 estabelece que a suspensão não pode exceder 60 dias consecutivos.',
  //----------------------------------
  'pergunta_142':'Quem pode determinar a instauração de sindicância?',
  'pergunta_142_alternativa_1':'Somente o Prefeito.',
  'pergunta_142_alternativa_2':'A autoridade que tiver conhecimento da irregularidade.',
  'pergunta_142_alternativa_3':'Apenas o chefe imediato do servidor.',
  'pergunta_142_alternativa_4':'A Câmara de Vereadores.',
  'pergunta_142_resposta_correta':'A autoridade que tiver conhecimento da irregularidade.',
  'pergunta_142_justificativa':'O art. 150 determina que a autoridade que tomar conhecimento de irregularidade deve promover imediata apuração.',
  //----------------------------------
  'pergunta_143':'O servidor poderá requerer revisão de processo disciplinar por meio de:',
  'pergunta_143_alternativa_1':'Pedido escrito fundamentado, dirigido à autoridade competente.',
  'pergunta_143_alternativa_2':'Comunicação verbal ao chefe imediato.',
  'pergunta_143_alternativa_3':'Representação sindical.',
  'pergunta_143_alternativa_4':'Decisão judicial sumária.',
  'pergunta_143_resposta_correta':'Pedido escrito fundamentado, dirigido à autoridade competente.',
  'pergunta_143_justificativa':'A revisão depende de requerimento formal e fundamentado, conforme art. 166.',
  //----------------------------------
  'pergunta_144':'É vedado ao servidor público municipal:',
  'pergunta_144_alternativa_1':'Cometer a estranhos encargos que lhe competirem.',
  'pergunta_144_alternativa_2':'Cumprir ordens de superiores hierárquicos.',
  'pergunta_144_alternativa_3':'Atuar com eficiência no serviço.',
  'pergunta_144_alternativa_4':'Usar uniforme funcional.',
  'pergunta_144_resposta_correta':'Cometer a estranhos encargos que lhe competirem.',
  'pergunta_144_justificativa':'O art. 115, I, proíbe ao servidor cometer a pessoas estranhas à repartição encargos que lhe competirem.',
  //----------------------------------
  'pergunta_145':'O servidor poderá ser aposentado:',
  'pergunta_145_alternativa_1':'Por invalidez permanente.',
  'pergunta_145_alternativa_2':'A pedido, por tempo de contribuição.',
  'pergunta_145_alternativa_3':'Compulsoriamente aos 75 anos.',
  'pergunta_145_alternativa_4':'Todas as alternativas estão corretas.',
  'pergunta_145_resposta_correta':'Todas as alternativas estão corretas.',
  'pergunta_145_justificativa':'A LC 3.673/91 prevê as hipóteses de aposentadoria: por invalidez, por tempo de contribuição e compulsória aos 75 anos.',
  //----------------------------------
  'pergunta_146':'É dever do servidor público:',
  'pergunta_146_alternativa_1':'Cumprir as ordens legais de seus superiores hierárquicos.',
  'pergunta_146_alternativa_2':'Agir conforme seu interesse particular.',
  'pergunta_146_alternativa_3':'Omitir-se em caso de irregularidades.',
  'pergunta_146_alternativa_4':'Recusar ordens legais.',
  'pergunta_146_resposta_correta':'Cumprir as ordens legais de seus superiores hierárquicos.',
  'pergunta_146_justificativa':'Conforme o art. 113, é dever do servidor cumprir ordens legais de superiores.',
  //----------------------------------
  'pergunta_147':'A licença para desempenho de mandato classista poderá ser concedida:',
  'pergunta_147_alternativa_1':'Por até 2 anos, sem remuneração.',
  'pergunta_147_alternativa_2':'Com remuneração, enquanto durar o mandato.',
  'pergunta_147_alternativa_3':'Por até 4 anos, com vencimentos.',
  'pergunta_147_alternativa_4':'Apenas aos dirigentes de entidades religiosas.',
  'pergunta_147_resposta_correta':'Com remuneração, enquanto durar o mandato.',
  'pergunta_147_justificativa':'A LC 3.673/91 prevê licença com vencimentos para exercício de mandato classista.',
  //----------------------------------
  'pergunta_148':'O servidor público que causar dano à Administração deverá:',
  'pergunta_148_alternativa_1':'Responder civil, penal e administrativamente.',
  'pergunta_148_alternativa_2':'Apenas ser advertido.',
  'pergunta_148_alternativa_3':'Restituir o dano, mas sem responsabilidade penal.',
  'pergunta_148_alternativa_4':'Ficar isento de penalidade se for servidor estável.',
  'pergunta_148_resposta_correta':'Responder civil, penal e administrativamente.',
  'pergunta_148_justificativa':'Conforme o art. 129, o servidor responde por dano causado à Administração em todas essas esferas.',
  //----------------------------------
  'pergunta_149':'A cassação de aposentadoria será aplicada quando:',
  'pergunta_149_alternativa_1':'O servidor praticar falta grave antes da aposentadoria.',
  'pergunta_149_alternativa_2':'O servidor acumular licenças.',
  'pergunta_149_alternativa_3':'Aposentadoria for indevida por erro administrativo.',
  'pergunta_149_alternativa_4':'Em caso de promoção indevida.',
  'pergunta_149_resposta_correta':'O servidor praticar falta grave antes da aposentadoria.',
  'pergunta_149_justificativa':'O art. 144 prevê cassação da aposentadoria se o servidor cometeu falta grave no exercício do cargo.',
  //----------------------------------
  'pergunta_150':'De acordo com a LC 3.673/91, o servidor será demitido se:',
  'pergunta_150_alternativa_1':'Cometer insubordinação grave ou reiterada.',
  'pergunta_150_alternativa_2':'Cometer ofensa física em serviço.',
  'pergunta_150_alternativa_3':'Abandonar o cargo por mais de 30 dias.',
  'pergunta_150_alternativa_4':'Todas as alternativas estão corretas.',
  'pergunta_150_resposta_correta':'Todas as alternativas estão corretas.',
  'pergunta_150_justificativa':'O art. 143 lista todas essas hipóteses como passíveis de demissão.',
  //----------------------------------

    
}

